5733d9e2be6485d52ffa08870cabdee0/sandbox

manager/src/test/java/com/redhat/developer/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/developer/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/developer/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/developer/manager/models/ProcessorTest.java
Small refactoring while implementing some other stuff
=> MGDOBR-6-refactoring: refactoring

kustomize/overlays/prod/kustomization.yaml
=> [903af] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [a914d] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [09711] Update kustomization images

.github/pull_request_template.md
Adds a template for pull requests. Nothing more to say :-)
=> [No Issue] Add a template for pull requests

kustomize/overlays/prod/kustomization.yaml
=> [dfe7c] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [32ee4] Update kustomization images

infra/src/main/java/com/redhat/service/bridge/infra/k8s/K8SBridgeConstants.java, infra/src/main/java/com/redhat/service/bridge/infra/k8s/KubernetesResourceType.java, infra/src/main/java/com/redhat/service/bridge/infra/k8s/ResourceEvent.java, k8s/src/main/java/com/developer/service/bridge/k8s/CustomResourceManagerImpl.java, k8s/src/main/java/com/developer/service/bridge/k8s/DeploymentsManagerImpl.java, k8s/src/main/java/com/developer/service/bridge/k8s/KubernetesUtils.java, k8s/src/main/java/com/developer/service/bridge/k8s/NetworkManagerImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/BridgesService.java, manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorService.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java, manager/src/test/java/com/redhat/service/bridge/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/service/bridge/manager/models/ProcessorTest.java, manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java, runner/src/test/java/com/redhat/service/bridge/runner/it/End2EndTestIT.java, shard/src/main/java/com/redhat/service/bridge/shard/ManagerSyncServiceImpl.java, shard/src/main/java/com/redhat/service/bridge/shard/controllers/IngressController.java, shard/src/main/java/com/redhat/service/bridge/shard/controllers/ProcessorController.java, shard/src/test/java/com/redhat/service/bridge/shard/controllers/ProcessorControllerTest.java
[MGDOBR-8](https://issues.redhat.com/browse/MGDOBR-8) 
=> MGDOBR-8: Add processor delete operation in manager and shard

kustomize/overlays/prod/kustomization.yaml
=> [f401e] Update kustomization images

DEMO.md, FILTERS.md, README.md, kustomize/README.md
[MGDOBR-47](https://issues.redhat.com/browse/MGDOBR-47)
This PR aims to add the instructions for a demo.  
=> MGDOBR-47: add demo and filters documentation

kustomize/overlays/prod/kustomization.yaml
=> [34bdb] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [af2a0] Update kustomization images

.github/pull_request_template.md
Link not applicable.
Small update to the pull request template for the project to help new team members with their commit messages and also the Assertions framework to use when writing tests.
=> [No Issue] Further updates to PR template to help new team members

kustomize/overlays/prod/kustomization.yaml
=> [29a3c] Update kustomization images

build-parent/pom.xml, manager/pom.xml, manager/src/main/java/com/redhat/service/bridge/manager/CustomerIdResolver.java, manager/src/main/java/com/redhat/service/bridge/manager/CustomerIdResolverImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java, manager/src/test/java/com/redhat/service/bridge/manager/CustomerIdResolverTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, runner/pom.xml, runner/src/test/java/com/redhat/service/bridge/runner/it/End2EndTestIT.java, runner/src/test/java/com/redhat/service/bridge/runner/it/KeycloakResource.java, runner/src/test/resources/application.properties, runner/src/test/resources/testcontainers/keycloak/realm.json
[MGDOBR-61](https://issues.redhat.com/browse/MGDOBR-61) 
=> MGDOBR-61: Add authentication to user API

kustomize/overlays/prod/kustomization.yaml
=> [1634b] Update kustomization images

infra/src/main/java/com/redhat/service/bridge/infra/utils/CloudEventUtils.java, ingress/src/main/java/com/redhat/service/bridge/ingress/api/exceptions/BadRequestException.java, ingress/src/main/java/com/redhat/service/bridge/ingress/producer/KafkaEventPublisher.java, ingress/src/test/java/com/redhat/service/bridge/ingress/TestUtils.java, ingress/src/test/java/com/redhat/service/bridge/ingress/api/IngressAPITest.java, ingress/src/test/java/com/redhat/service/bridge/ingress/producer/KafkaEventPublisherTest.java
[MGDOBR-35](https://issues.redhat.com/browse/MGDOBR-35) 
=> MGDOBR-35: block input events containing reserved attributes

kustomize/overlays/prod/kustomization.yaml
=> [c550c] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [49163] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [8a956] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [08af7] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [a69ba] Update kustomization images

shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressController.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
[MGDOBR-117](https://issues.redhat.com/browse/MGDOBR-117) 
=> MGDOBR-117: BridgeIngressController extracts endpoint, populates CRD and notifies the manager

kustomize/overlays/prod/kustomization.yaml
=> [eee24] Update kustomization images

FILTERS.md
=> [No-ticket] Fix typo in FILTERS.md

kustomize/overlays/prod/kustomization.yaml
=> [bd0de] Update kustomization images

shard-operator/README.md, shard-operator/pom.xml, shard-operator/src/main/resources/application.properties, shard-operator/src/test/resources/application.properties
[MGDOBR-148](https://issues.redhat.com/browse/MGDOBR-148) 
=> MGDOBR-148: add openshift profile and fix subject.namespace resources

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [cae40] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [be2d4] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [ab0f9] Update kustomization images

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [97a2c] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/actions/sendtobridge/SendToBridgeActionTransformer.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/sendtobridge/BridgeWebhookUrlTest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/sendtobridge/SendToBridgeActionTransformerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPITest.java
[MGDOBR-134](https://issues.redhat.com/browse/MGDOBR-134) 
=> MGDOBR-134: fix bridge webhook in SendToBridge action

kustomize/overlays/prod/kustomization.yaml
=> [6d3a5] Update kustomization images

DEMO.md
=> [no-ticket] Update DEMO.md

kustomize/overlays/prod/kustomization.yaml
=> [5224f] Update kustomization images

shard-operator-integration-tests/src/test/resources/features/bridgeingress-deploy.feature, shard-operator/src/main/resources/templates/bridge-executor-deployment.yaml, shard-operator/src/main/resources/templates/bridge-ingress-deployment.yaml, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/providers/TemplateProviderTest.java
[MGDOBR-72](https://issues.redhat.com/browse/MGDOBR-72) 
This PR aims to add the liveness and readiness probe checks to the ingress and executor deployements.
=> MGDOBR-72: add liveness and readiness probe checks to ingress and executor deployments

kustomize/overlays/prod/kustomization.yaml
=> [a8e14] Update kustomization images

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [b4fb4] Update kustomization images

DEMO.md, README.md, dev/README.md
This PR simply updates a few of the project `README.md` documents after completing a run-through of the demo on a Mac.
=> [No Issue] Updated local development instructions following run-through on Mac

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [c5eb1] Update kustomization images

build-parent/pom.xml
=> [NO TICKET] fix maven.compiler.release

kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml, kustomize/base/shard/resources/bridgeingresses.com.redhat.service.bridge-v1.yml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [ceae4] Update kustomization images

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/cluster-role.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [b411f] Update kustomization images

kustomize/base/manager/resources/deploy.yaml, kustomize/base/manager/resources/keycloak.yaml, kustomize/base/manager/resources/postgres.yaml, kustomize/overlays/prod/manager/patches/deploy-config.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
[MGDOBR-189](https://issues.redhat.com/browse/MGDOBR-189) 
This PR adds an additional label called `app-component` to all parts of the `manager` base in Kustomize and ensures that service selectors match on both labels e.g `app=event-bridge;app-component=fleet-manager`
=> [MGDOBR-189] Update Service Selectors and ensure correct client Id for SSO

manager/src/main/resources/application.properties, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceImpl.java
[MGDOBR-190](https://issues.redhat.com/browse/MGDOBR-190) 
=> MGDOBR-190: fix shard authentication

kustomize/overlays/prod/kustomization.yaml
=> [e9bf2] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [cbbfe] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [5ea73] Update kustomization images

kustomize/overlays/prod/kustomization.yaml
=> [fea99] Update kustomization images

dev/README.md
[MGDOBR-203](https://issues.redhat.com/browse/MGDOBR-203) 
Update local dev setup README for Prometheus
=> [MGDOBR-203] Update local dev setup README for Prometheus

dev/README.md
=> update instructions for the mac

.github/workflows/Operator-CI.yaml, kustomize/README.md, kustomize/base/keycloak/kustomization.yaml, kustomize/base/keycloak/resources/keycloak.yaml, kustomize/base/kustomization.yaml, kustomize/base/manager/kustomization.yaml, kustomize/overlays/minikube/kafka/kafka-topics.yaml, kustomize/overlays/minikube/kafka/kafka.yaml, kustomize/overlays/minikube/kafka/kustomization.yaml, kustomize/overlays/minikube/kafka/namespace.yaml, kustomize/overlays/minikube/kafka/strimzi.yaml, kustomize/overlays/minikube/keycloak/event-bridge-fm-realm-sample.json, kustomize/overlays/minikube/keycloak/kustomization.yaml, kustomize/overlays/minikube/keycloak/namespace.yaml, kustomize/overlays/minikube/keycloak/nodeport.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/manager/ingress.yaml, kustomize/overlays/minikube/manager/kustomization.yaml, kustomize/overlays/minikube/manager/namespace.yaml, kustomize/overlays/minikube/manager/patches/deploy-config.yaml, kustomize/overlays/minikube/manager/patches/postgres-config.yaml, kustomize/overlays/minikube/prometheus/kustomization.yaml, kustomize/overlays/minikube/shard/cluster-role-binding.yaml, kustomize/overlays/minikube/shard/cluster-role.yaml, kustomize/overlays/minikube/shard/kustomization.yaml, kustomize/overlays/minikube/shard/namespace.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, manager/src/main/resources/application.properties, shard-operator/src/main/resources/application.properties
[MGDOBR-188](https://issues.redhat.com/browse/MGDOBR-188) 
Refactored kustomize script to support deploying all components into local Minikube cluster.
Pending tasks:
- Publish minikube operator image?
=> MGDOBR-188 Create kustomize overlays for basic usage scenarios

.github/workflows/CD.yml
[MGDOBR-211](https://issues.redhat.com/browse/MGDOBR-211) 
Untested as the script is triggered by main branch push. Implementation inspired by other commands in file, hopefully should be syntactically correct.
The operator is rebuilt as we need to produce application using different profile, pushed into same repository with tag prefix.
=> MGDOBR-211 Publish operator image built with Minikube profile

.github/workflows/CD.yml
[MGDOBR-221](https://issues.redhat.com/browse/MGDOBR-221) 
=> MGDOBR-221: fix CD pipeline

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [8120f] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [5fa2c] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [e2c45] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [f89f8] Update kustomization images

build-parent/pom.xml, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/utils/LabelsBuilder.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
=> Update quarkus/operator-sdk dependencies

executor/src/main/java/com/redhat/service/bridge/executor/Executor.java, executor/src/main/java/com/redhat/service/bridge/executor/ExecutorsK8SDeploymentManager.java, executor/src/main/java/com/redhat/service/bridge/executor/ExecutorsService.java, executor/src/main/java/com/redhat/service/bridge/executor/transformations/TransformationEvaluatorQute.java, ingress/src/main/java/com/redhat/service/bridge/ingress/api/IngressAPI.java, ingress/src/main/java/com/redhat/service/bridge/ingress/producer/KafkaEventPublisher.java, manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressController.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/KubernetesNetworkingService.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/OpenshiftNetworkingService.java
[MGDOBR-228](https://issues.redhat.com/browse/MGDOBR-228)
Removed unnecessary component prefixes on log statements across the project. 
=> [MGDOBR-228] Removed unnecessary component prefixes on log statements

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClient.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClientImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsService.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/dao/ConnectorsDAO.java, manager/src/main/java/com/redhat/service/bridge/manager/models/ConnectorEntity.java, manager/src/main/resources/application.properties, manager/src/main/resources/db/migration/0.1/V0.1.3__create_connectors.sql, manager/src/main/resources/db/migration/0.1/V0.1.4__update_connectors.sql, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
* External MC id column in the connector table
* Changed default values for MC configuration
[MGDOBR-200](https://issues.redhat.com/browse/MGDOBR-200) 
=> MGDOBR-200 MC: Delete the Managed Connector when the user deletes the associated Processor

shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/logs/LogCollector.java
[MGDOBR-214](https://issues.redhat.com/browse/MGDOBR-214) 
Fixing race condition in teardown procedure of cucumber tests (retrieving logs of pod being deleted).
=> MGDOBR-214 Ignore exception thrown when retrieving pod logs in tests

.github/workflows/CD.yml
=> Update CD pipelines with new modules

shard-operator/src/main/resources/templates/bridge-ingress-openshift-route.yaml
[MGDOBR-183](https://issues.redhat.com/browse/MGDOBR-183) 
=> MGDOBR-183: add https to ingress application

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [a83cc] Update kustomization images

.github/workflows/Operator-CI.yaml, dev/README.md, manager/src/main/resources/application.properties, shard-operator/src/main/resources/application.properties, shard-operator/src/test/resources/application.properties
[MGDOBR-227](https://issues.redhat.com/browse/MGDOBR-227) 
=> MGDOBR-227: dynamic configuration of manager and shard sso for dev

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [d001b] Update kustomization images

kustomize/README.md
Operator image is updated automatically.
=> Remove operator image mention from kustomize readme for Minikube

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [b7058] Update kustomization images

kustomize/overlays/minikube/manager/patches/deploy-config.yaml, kustomize/overlays/minikube/shard/kustomization.yaml, manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/test/java/com/redhat/service/bridge/manager/DefaultJsonWebToken.java, manager/src/test/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java
[MGDOBR-248](https://issues.redhat.com/browse/MGDOBR-248) 
=>  MGDOBR-248: Fix shard authentication

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [313d0] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [40eee] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [8fafc] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/RhoasService.java, manager/src/main/java/com/redhat/service/bridge/manager/RhoasServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/ConnectorAction.java, manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackAction.java, manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTransformer.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsService.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsServiceImpl.java, manager/src/test/java/com/redhat/service/bridge/manager/RhoasServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTransformerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/connectors/ConnectorsServiceTest.java
[MGDOBR-139](https://issues.redhat.com/browse/MGDOBR-139) 
Replaces #227 
=> MGDOBR-139: create Kafka topic for Slack action

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [04816] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [7db84] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [bb1a4] Update kustomization images

manager/src/main/resources/application.properties
=> Fix health check

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [a8387] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTransformer.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTransformerTest.java
[MGDOBR-139](https://issues.redhat.com/browse/MGDOBR-139) 
=> MGDOBR-139: fix connector+topic deletion in SlackAction

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [eba85] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [3d9a3] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackAction.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTest.java
[MGDOBR-276](https://issues.redhat.com/browse/MGDOBR-276) 
=> MGDOBR-276: fix managed connector creation

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [e2d35] Update kustomization images

kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml, kustomize/base/shard/resources/bridgeingresses.com.redhat.service.bridge-v1.yml
=> [6f760] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [e689a] Update kustomization images

kustomize/overlays/minikube/shard/cluster-role.yaml, kustomize/overlays/prod/shard/cluster-role.yaml
[MGDOBR-171](https://issues.redhat.com/browse/MGDOBR-171) 
=> [MGDOBR-171] Add cluster role secret rights to kustomize

infra/src/main/java/com/redhat/service/bridge/infra/models/dto/BridgeStatus.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
[MGDOBR-279](https://issues.redhat.com/browse/MGDOBR-279) 
=> [MGDOBR-279] add DELETING status

.github/actions/kind/action.yml, .github/kind-config.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, integration-tests/README.md, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeUtils.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/End2EndTestITStep.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/KubernetesNetworkingService.java
[MGDOBR-206](https://issues.redhat.com/browse/MGDOBR-206) 
The pipeline builds complete repository, deploys all images into KinD, installs environment using kustomize and executes integration tests against deployed environment.
Fixed minor issue in operator revealed by tests.
=> MGDOBR-206 Create CI pipeline to execute E2E BDD tests

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [bfd11] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [b6df8] Update kustomization images

kustomize/overlays/prod/shard/cluster-role.yaml
[MGDOBR-271](https://issues.redhat.com/browse/MGDOBR-271) 
Addressing leftover from https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/278
=> MGDOBR-271 Add custom host and ingress config rights to kustomize

build-parent/pom.xml, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClient.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClientImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsServiceImpl.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
=> MGDOBR-249 Update Connector SDK

dev/README.md
=> Update dev readme to reflect current deployments

.github/workflows/codeql-analysis.yml
[MGDOBR-297](https://issues.redhat.com/browse/MGDOBR-297) 
See https://github.com/r00ta/sandbox/pull/4/files for an example result 
=> MGDOBR-297: add codeql pipeline

shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/BridgeIngressServiceTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/EventBridgeOidcClientTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorControllerTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressControllerTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/monitoring/ServiceMonitorServiceTest.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/providers/CustomerNamespaceProviderImplTest.java
[MGDOBR-299](https://issues.redhat.com/browse/MGDOBR-299) 
=> MGDOBR-299: fix flasky tests in shard operator

.github/pull_request_template.md, .github/workflows/Manager-CI.yaml
[MGDOBR-300](https://issues.redhat.com/browse/MGDOBR-300) 
Together with @sutaakar we spotted that the Setup Java And Manen step is checking out the `main` branch of the original repository again. So we have to checkout the code again after that step 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-300] Update Manager-CI.yaml

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [3ea22] Update kustomization images

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/End2EndTestITStep.java, integration-tests/src/test/resources/features/end2endtestit.feature
[MGDOBR-302](https://issues.redhat.com/browse/MGDOBR-302) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-302 Refactor and stabilize metrics in integration tests

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [c78e9] Update kustomization images

manager/src/main/resources/application.properties
[MGDOBR-315](https://issues.redhat.com/browse/MGDOBR-315) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-315: suppress kafka warnings in the manager

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [4c0d6] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [88ca2] Update kustomization images

dev/bin/kafka-setup.sh
[MGDOBR-296](https://issues.redhat.com/browse/MGDOBR-296) 
This is a fix for `kafka-setup.sh` dev script.
**Issue description:** if the kafka instance is recreated but the service accounts are already completely configured and the credentials files are present, the ACLs won't be applied to the newly created instance, leaving the service accounts unusable.
=> MGDOBR-296: fix kafka-setup script with instance creation detection

shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorControllerTest.java
[MGDOBR-320](https://issues.redhat.com/browse/MGDOBR-320) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-320: notify manager when deployment of executor fails

kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/manager/patches/deploy.yaml
[MGDOBR-232](https://issues.redhat.com/browse/MGDOBR-232) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-232: patch manager deployment with cpu and memory requests and limits

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [8f3db] Update kustomization images

kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [55563] Update kustomization images

ACTIONS.md
<details>
<summary>
</summary>
</details>
=> [NO TICKET] Update ACTIONS.md fix typo

ACTIONS.md
Current wording could mislead users.
<details>
<summary>
</summary>
</details>
=> Replace properties with parameters in Actions readme

manager/src/main/java/com/redhat/service/bridge/manager/connectors/AbstractConnectorWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/connectors/ConnectorsOrchestratorImplTest.java
[MGDOBR-199](https://issues.redhat.com/browse/MGDOBR-199) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-199 better logging for AbstractConnectorWorker

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [f6f96] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [4bcef] Update kustomization images

dev/README.md
Alternative link for RHOAS CLI installation page
> [Insert JIRA Issue number and update link](https://issues.redhat.com/browse/MGDOBR-) 
> 
> Please make sure that your PR meets the following requirements:
> 
> - [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
> - [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
> - [ ] All new functionality is tested
> - [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
> - [ ] Pull Request contains link to the JIRA issue
> - [ ] Pull Request contains link to any dependent or related Pull Request
> - [ ] Pull Request contains description of the issue
> - [ ] Pull …
=> Alternative link for RHOAS CLI installation page

dev/bin/minikube-build-docker-images.sh, dev/bin/minikube-start.sh, kustomize/cleanMinikubeDeployLocalDev.sh
[MGDOBR-350](https://issues.redhat.com/browse/MGDOBR-350) 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-350] Correct minikube scripts

manager/src/main/java/com/redhat/service/bridge/manager/api/user/BridgesAPI.java
[MGDOBR-333](https://issues.redhat.com/browse/MGDOBR-333) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-333: update openapi

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [b9045] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [28bfc] Update kustomization images

.github/workflows/dev-cluster-check.yml, DEMO.md, build-parent/pom.xml, dev/bin/configure.sh, dev/bin/manager-run.sh, integration-tests/README.md, integration-tests/pom.xml, integration-tests/run-local-tests.sh, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeUtils.java, kustomize/README.md, kustomize/startMinikubeDeployLocalDev.sh, shard-operator-integration-tests/pom.xml
[MGDOBR-348](https://issues.redhat.com/browse/MGDOBR-348) 
Issue splitted into different PRs for better review:
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/364
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/365
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/366
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/367
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/368
<details>
<summary>
</summary>
* <b>Rebase the pull request</b> …
=> [MGDOBR-348] Setup run local script for integration tests

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [0ffa5] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [c998a] Update kustomization images

actions/src/main/resources/application.properties, dev/bin/manager-run.sh
This property shouldn't be used, and it triggered a bug previously
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] Removed useless property

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [bdbfb] Update kustomization images

dev/bin/manager-run.sh
Disable all Dev services for Manager.
[MGDOBR-360](https://issues.redhat.com/browse/MGDOBR-360) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-360 Disable Quarkus Dev services for Manager

ACTIONS.md, DEMO.md, infra/src/main/java/com/redhat/service/bridge/infra/models/actions/BaseAction.java, integration-tests/src/test/resources/features/end2endtestit.feature, manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionTransformer.java, manager/src/main/java/com/redhat/service/bridge/manager/actions/sendtobridge/SendToBridgeActionTransformer.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/validators/actions/ActionParamValidatorContainer.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/TestConstants.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionValidatorTest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/sendtobridge/SendToBridgeActionTransformerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/sendtobridge/SendToBridgeActionValidatorTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/validators/actions/ActionParamValidatorContainerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/connectors/ConnectorsServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/dao/ConnectorsDAOTest.java, manager/src/test/java/com/redhat/service/bridge/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/service/bridge/manager/utils/Fixtures.java, manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java, openapi/openapi.yaml, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/TestSupport.java
See [MGDOBR-316](https://issues.redhat.com/browse/MGDOBR-316) 
I updated `DEMO.md` and `ACTIONS.md` too. I also regenerated `openapi.yaml`.
<details>
<summary>
</summary>
</details>
=> MGDOBR-316: Remove 'name' field from Action definition on the Processor API

FILTERS.md
The description of the FILTERS is not totally clear.
I reworded some unclear parts and added an example for combining individual filter entries.
=> Some clarifications

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [acc00] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [2e5ce] Update kustomization images

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeUtils.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/ProcessorContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ManagerSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/MetricsSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ProcessorSteps.java, integration-tests/src/test/resources/features/end2endtestit.feature, kustomize/cleanMinikubeDeployLocalDev.sh
[MGDOBR-358](https://issues.redhat.com/browse/MGDOBR-358) 
In that PR, we can have multiple bridge and multiple processors per bridge.
Scenario steps are also redefined.
<details>
<summary>
</summary>
</details>
=> [MGDOBR-358] refactor features to have more flexible context

DEMO.md
No Jira
<details>
<summary>
</summary>
</details>
=> Update guide to show how to publish messages to Slack

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
[MGDOBR-372](https://issues.redhat.com/browse/MGDOBR-372) 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-372] Return a HTTP 404 Status Code when deleting a Processor that does not exist.

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [efd0e] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionValidator.java, manager/src/main/java/com/redhat/service/bridge/manager/api/models/requests/ProcessorRequest.java, manager/src/test/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionValidatorTest.java
[Creating a SlackAction without parameters gives an Internal server error](https://issues.redhat.com/browse/MGDOBR-312) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-312 Creating a SlackAction without parameters gives an Internal server error

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [72f99] Update kustomization images

ingress/src/main/java/com/redhat/service/bridge/ingress/api/IngressAPI.java
[MGDOBR-390](https://issues.redhat.com/browse/MGDOBR-390) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-390 Make ce-subject header optional in plain endpoint

kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [c464c] Update kustomization images

.github/workflows/Manager-CI.yaml, .github/workflows/labels-check.yml, infra/pom.xml
[MGDOBR-392](https://issues.redhat.com/browse/MGDOBR-392) 
This PR aims to enforce the presence of the `safe to test` label on PR. I've seen we merged some PR without having the Manager CI check, so this should enforce it. 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-392] Add check label ci

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [c6913] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [d5a43] Update kustomization images

.github/workflows/Manager-CI.yaml
[MGDOBR-400](https://issues.redhat.com/browse/MGDOBR-400) 
<details>
<summary>
</summary>
</details>
=> Apply Slack secrets to the slack environment variables

.github/workflows/Manager-CI.yaml
[MGDOBR-405](https://issues.redhat.com/browse/MGDOBR-405)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-405] Create and enable Manage connector secrets for tests using MC

.github/workflows/Manager-CI.yaml
<details>
<summary>
</summary>
</details>
=> fix manager-ci path failure

app-interface/app_sre_build_push.sh
[MGDOBR-402](https://issues.redhat.com/browse/MGDOBR-402) 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-402] Add appsre script to build and push fleet manager image

kustomize/overlays/prod/manager/patches/deploy.yaml
<details>
<summary>
</summary>
</details>
=> MGDOBR-409: fix manager resource request/limit

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [9cbd0] Update kustomization images

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/AwaitilityOnTimeOutHandler.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/AwaitilityOnTimeOutLogger.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/BridgeResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/IngressResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/ProcessorResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ProcessorSteps.java
[MGDOBR-387](https://issues.redhat.com/browse/MGDOBR-387) 
Rest calls are logged when there is an issue in the check. This will help for investigation.
<details>
<summary>
</summary>
</details>
=> [MGDOBR-387] Integration tests: Improve REST logging when REST failure occurs

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java, integration-tests/src/test/resources/features/ingress.feature
[MGDOBR-385](https://issues.redhat.com/browse/MGDOBR-385) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-385 Generate and persist cloud event attributes for integration tests

shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
Should help analyzing logs to identify test instabilities
<details>
<summary>
</summary>
</details>
=> Adjust Bridge names in ManagerSyncServiceTest to be unique

manager/src/main/java/com/redhat/service/bridge/manager/BridgesService.java, manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/providers/InternalKafkaConfigurationProvider.java, manager/src/main/java/com/redhat/service/bridge/manager/providers/InternalKafkaConfigurationProviderImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/BridgeWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/BridgeWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-363](https://issues.redhat.com/browse/MGDOBR-363) 
<details>
<summary>
</summary>
</details>
=> MGDBOR-363: Refactor Bridge provisioning to re-use resilient mechanism 

.github/pull_request_template.md, .github/workflows/Manager-CI.yaml
[MGDOBR-428](https://issues.redhat.com/browse/MGDOBR-428)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-428] Update PR template

.github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml
[MGDOBR-304](https://issues.redhat.com/browse/MGDOBR-304)
<details>
<summary>
</summary>
</details>
=> MGDOBR-304 Add Slack secrets into GitHub action scripts

manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClient.java, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClientImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/connectors/ConnectorsApiClientTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorkerTest.java
See [MGDOBR-434](https://issues.redhat.com/browse/MGDOBR-434) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-434: ConnectorsApi.getConnector() returns 404 if not found and not null

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [3b059] Update kustomization images

.github/workflows/CI.yaml
This PR aims to disable the CI check for those PR that don't need it
<details>
<summary>
</summary>
</details>
=> [no ticket] Update CI.yaml

manager/src/main/resources/application.properties
<details>
<summary>
</summary>
</details>
=> MGDOBR-438: enable cors

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [19ba7] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [90dcf] Update kustomization images

integration-tests/README.md, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/resolver/CloudEventIdResolver.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/resolver/SystemPropertyResolver.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/SlackResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ProcessorSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/SlackSteps.java, integration-tests/src/test/resources/features/processor-template.feature
[MGDOBR-347](https://issues.redhat.com/browse/MGDOBR-347)
<details>
<summary>
</summary>
</details>
=> MGDOBR-347 Integration test checking Transformations functionality

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/ProcessorContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ProcessorSteps.java
[MGDOBR-443](https://issues.redhat.com/browse/MGDOBR-443)
<details>
<summary>
</summary>
</details>
=> MGDOBR-443 Log generated ids in context for better debugging

.github/workflows/CI.yaml, app-interface/manifests/rhose-flee-manager.yml
See: https://issues.redhat.com/browse/MGDOBR-440
<details>
<summary>
</summary>
</details>
=> [MGDOBR-440] - Create RHOSE Openshift Template

app-interface/manifests/rhose-flee-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - fix image tag openshift template

manager/src/main/resources/application.properties
[MGDOBR-453](https://issues.redhat.com/browse/MGDOBR-453)
To help with us with debugging the resource provisioning, this PR enables `DEBUG` level logging for all Workers.
<details>
<summary>
</summary>
</details>
=> [MGDOBR-453] Enable DEBUG logging for Workers in all environments

.github/workflows/dev-cluster-check.yml
<details>
<summary>
</summary>
</details>
=> Manually trigger dev cluster check action

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [f741b] Update kustomization images

app-interface/manifests/rhose-flee-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - remove param from template

manager/src/main/java/com/redhat/service/bridge/manager/BridgesService.java, manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/dao/BridgeDAO.java, manager/src/main/java/com/redhat/service/bridge/manager/models/Bridge.java, manager/src/test/java/com/redhat/service/bridge/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/dao/BridgeDAOTest.java
[https://issues.redhat.com/browse/MGDOBR-449](https://issues.redhat.com/browse/MGDOBR-449)
<details>
<summary>
</summary>
</details>
=> MGDOBR-449: The manager asks the shard to provision/delete instances before the dependencies are created

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [66b92] Update kustomization images

kustomize/overlays/stable/kustomization.yaml
<details>
<summary>
</summary>
</details>
=> [5e8155d] Update stable kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/workers/WorkManagerImpl.java, manager/src/test/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncSegmentationAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/WorkManagerImplTest.java
[https://issues.redhat.com/browse/MGDOBR-362](https://issues.redhat.com/browse/MGDOBR-362)
<details>
<summary>
</summary>
</details>
=> MGDOBR-436: Workers: Interleaved execution for same work

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [b2c9a] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/ProcessorWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-446](https://issues.redhat.com/browse/MGDOBR-446)
<details>
<summary>
</summary>
</details>
=> MGDOBR-446: Processor with Failed dependencies is not marked as Failed

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [55c38] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/workers/WorkManagerImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/AbstractWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/AbstractWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-454](https://issues.redhat.com/browse/MGDOBR-454)
<details>
<summary>
</summary>
</details>
=> MGDOBR-454: Work is never removed from the queue if the entity has been deleted

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [f3a59] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorkerTest.java
[MGDOBR-464](https://issues.redhat.com/browse/MGDOBR-464)
<details>
<summary>
</summary>
</details>
=> MGDOBR-464: delete connector even if it is in failed state

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [1c662] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/workers/resources/AbstractWorker.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/AbstractWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-433](https://issues.redhat.com/browse/MGDOBR-433)
<details>
<summary>
</summary>
</details>
=> MGDOBR-433: Work is never removed from the queue if max attempts is exceeded

.github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml
[MGDOBR-305](https://issues.redhat.com/browse/MGDOBR-305)
This PR is to prepare new environment variables for #494
<details>
<summary>
</summary>
</details>
=> MGDOBR-305: Prepare new CI env variable

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [c7cb5] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/ErrorsAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java, openapi/openapi.yaml
<details>
<summary>
</summary>
</details>
=> [NO TICKET] remove api suffix from openapi

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [b0d68] Update kustomization images

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeUtils.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/IngressResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java, integration-tests/src/test/resources/features/action-slack.feature, integration-tests/src/test/resources/features/ingress.feature, integration-tests/src/test/resources/features/processor-template.feature, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/KubernetesNetworkingService.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/NetworkingConstants.java, shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/OpenshiftNetworkingService.java, shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-397](https://issues.redhat.com/browse/MGDOBR-397)
<details>
<summary>
</summary>
</details>
=> MGDOBR-397: Ingress endpoint exposed by the API is missing the  context path

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [dbe9d] Update kustomization images

dev/bin/localconfig-example, integration-tests/pom.xml, integration-tests/run-local-tests.sh, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/webhook/site/WebhookSiteRequest.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/webhook/site/WebhookSiteResource.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/ProcessorSteps.java, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/WebhookSiteSteps.java, integration-tests/src/test/resources/features/action-slack.feature, integration-tests/src/test/resources/features/action-webhook.feature
- https://issues.redhat.com/browse/MGDOBR-305
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/507
<details>
<summary>
</summary>
</details>
=> MGDOBR-305: Test Webhook action

dev/bin/interaction/README.MD
No JIRA.
<details>
<summary>
</summary>
</details>
=> Add note about dash vs bash

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [abfaf] Update kustomization images

integration-tests/src/test/resources/features/action-webhook.feature
[MGDOBR-305](https://issues.redhat.com/browse/MGDOBR-305)
Required due to https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/502
<details>
<summary>
</summary>
</details>
=> MGDOBR-305 Remove path from cloud event invocation step

manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/AbstractWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/BridgeWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-467](https://issues.redhat.com/browse/MGDOBR-467)
<details>
<summary>
</summary>
</details>
=> MGDOBR-467: Remove use of Mocking from ConnectorWorkerTest, BridgeWorkerTest and ProcessorWorkerTest

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [be527] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml, manager/src/main/java/com/redhat/service/bridge/manager/connectors/ConnectorsOidcClient.java
=> [a2c1c] Update kustomization images

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [891ef] Update kustomization images

.github/labeler.yml, .github/workflows/labels-check.yml
<details>
<summary>
</summary>
</details>
=> Label pipeline cleanup

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/resources/webhook/site/WebhookSiteResource.java
[[MGDOBR-493](https://issues.redhat.com/browse/MGDOBR-493)
webhook.site changed its api and our ManagerCI is broken by consequence. 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-493] Fix webhook.site response code in cucumber tests

.github/workflows/CI.yaml, .github/workflows/sonar.yaml, README.md, build-parent/pom.xml
- https://issues.redhat.com/browse/MGDOBR-282
<details>
<summary>
</summary>
</details>
=> MGDOBR-282: Analyze project by sonar

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [6aaf6] Update kustomization images

dev/bin/interaction/send-cloud-event.sh
After https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/commit/dbe9dea92f7fdc7939826f9d65d82101626c1817 there's no need to add this 
<details>
<summary>
</summary>
</details>
=> NO-JIRA removed /events suffix from bridge endpoint

kustomize/overlays/minikube/manager/kustomization.yaml
[MGDOBR-501](https://issues.redhat.com/browse/MGDOBR-501)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-501] update managed connectors stable url in minikube overlay

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [81697] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/workers/WorkManagerImpl.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/BridgeWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ConnectorWorkerTest.java, manager/src/test/java/com/redhat/service/bridge/manager/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-462](https://issues.redhat.com/browse/MGDOBR-462)
<details>
<summary>
</summary>
</details>
=> MGDOBR-462: Bridge/ProcessorServices: Improve split of create/delete methods X(..) and doX(..)

.github/workflows/sonar.yaml
[MGDOBR-495](https://issues.redhat.com/browse/MGDOBR-495)
<details>
<summary>
</summary>
</details>
=> MGDOBR-495: Disable shallow clone for sonar workflow

app-interface/app_sre_fleet_manager_build_push.sh, app-interface/buid_project.sh, docker/Dockerfile.appsre
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - adding Dockerfile to app-sre build process

.github/workflows/Manager-CI.yaml
<details>
<summary>
</summary>
</details>
=> Configure bearer token for cucumber tests

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [145f8] Update kustomization images

dev/README.md, dev/bin/localconfig-example, dev/bin/manager-run.sh
No Jira
<details>
<summary>
</summary>
</details>
=> NO-JIRA Update manager-run.sh to parametrize the MC control plane URL

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - adjust rhose template

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml
=> [8b4af] Update kustomization images

integration-tests/README.md
<details>
<summary>
</summary>
</details>
=> MGDOBR-500: Explain needed property for running Webhook Action tests

.github/workflows/CD.yml, .github/workflows/Manager-CI.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/labels-check.yml, .github/workflows/sonar.yaml
<details>
<summary>
</summary>
</details>
=> exclude app-interface directory from pipelines triggers

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - Update Template to add RDS secret reference

dev/bin/interaction/create-processor.sh
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Update create-processor script

.github/workflows/CI.yaml
[MGDOBR-541](https://issues.redhat.com/browse/MGDOBR-541)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-541] Use proper PR target for CI check

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [ad43f] Update kustomization images

infra/src/test/java/com/redhat/service/bridge/infra/BridgeErrorServiceTest.java
[MGDOBR-499](https://issues.redhat.com/browse/MGDOBR-499)
Replacement of #549 
<details>
<summary>
</summary>
</details>
=> MGDOBR-499: Fix wrong assertj calls order

kustomize/overlays/stable/kustomization.yaml, kustomize/overlays/stable/shard/patches/deploy-config.yaml
Deploy to staging this one 
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/596/files
We should probably automate this
<details>
<summary>
</summary>
</details>
=> [ad43f] Update kustomization images (stable)

integration-tests/pom.xml, integration-tests/run-local-tests.sh, integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeUtils.java
[MGDOBR-521](https://issues.redhat.com/browse/MGDOBR-521)
Token is updated in the integration tests. Tests are no longer failing because of expired token.
<details>
<summary>
</summary>
</details>
=> MGDOBR-521: Refresh sso token in integration tests execution

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [146a7] Update kustomization images

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorService.java, manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java, manager/src/main/java/com/redhat/service/bridge/manager/dao/ProcessorDAO.java, manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/bridge/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java, openapi/openapi.yaml
[https://issues.redhat.com/browse/MGDOBR-13](https://issues.redhat.com/browse/MGDOBR-13)
You can try updates to the `filter` using `HTTP PUT`. I have verified updated filters are deployed through our `Controller` and (in my test) a `Processor` configured to send events to Slack responded correctly to changes in the `Filter`.  
<details>
<summary>
</summary>
</details>
=> MGDOBR-13: Allow a user to update the Filter on a Sink Processor

.github/workflows/dev-cluster-check.yml
<details>
<summary>
</summary>
</details>
=> Fix CI issue in dev-cluster-check.yml

.github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, .github/workflows/dev-cluster-check.yml, integration-tests/pom.xml, shard-operator-integration-tests/pom.xml
[MGDOBR-377](https://issues.redhat.com/browse/MGDOBR-377) 
<details>
<summary>
</summary>
</details>
=> [MGDOBR-377] Run integration-tests in parallel

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java
<details>
<summary>
</summary>
</details>
=> [NO JIRA] E2E tests: Wait until Bridge is cleaned up

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/ProcessorResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ProcessorSteps.java, integration-tests/src/test/resources/features/ingress.feature, integration-tests/src/test/resources/features/processor-template.feature, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ProcessorsAPI.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ProcessorAPITest.java, openapi/openapi.yaml
[https://issues.redhat.com/browse/MGDOBR-515](https://issues.redhat.com/browse/MGDOBR-515)
<details>
<summary>
</summary>
</details>
=> MGDOBR-515: Allow a user to update the Transformation Template on a Sink Processor

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerClient.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerClientImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerClientTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceTest.java
Small refactoring for ManagerClient interface to add simple tests
<details>
<summary>
</summary>
</details>
=> Refactoring ManagerClient interface in shard

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [dff63] Update kustomization images

dev/bin/create-stable-pr.sh
[Create a script to make the PR to deploy to staging](https://issues.redhat.com/browse/MGDOBR-543)
I'm not sure why this scripts puts the quote in the kustomization.yaml but not in the deploy-config.yaml. It shouldn't be a big problem though
<details>
<summary>
</summary>
</details>
=> MGDOBR-543 Create a script to make the PR to deploy to staging

kustomize/startMinikubeDeployLocalDev.sh
The secret replacements weren't applied properly on Minikube environment, making it broken.
Moved kustomized script installation after value replacements to address the error.
<details>
<summary>
</summary>
</details>
=> Fix resource deployment in startMinikubeDeployLocalDev.sh

kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
=> [2d6d6] Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java
Original 2 minutes for Processor cleanup may not be enough for some cases, so extending the timeout to 4 minutes.
Using `untilAsserted` in the waiting loop to provide a context in case the waiting loop timeouts. In such case the timeout should return failing assertion containing what Processor/Bridge wasn't properly removed.
<details>
<summary>
</summary>
Comment with: …
=> Provide more context in E2E cleanup error logging

.github/actions/kind/action.yml, .github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, kustomize/README.md, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/networking/KubernetesNetworkingService.java
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] Setup machine hostname for Kind usage

ACTIONS.md, integration-tests/README.md, integration-tests/pom.xml, integration-tests/run-local-tests.sh, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/BridgeIdResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/CloudEventIdResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/Resolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/SystemPropertyResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/resources/features/action-sendtobridge.feature
[MGDOBR-307](https://issues.redhat.com/browse/MGDOBR-307)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-307] Integration-test for SendToBridgeAction

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceImpl.java
<details>
<summary>
</summary>
</details>
=> [NO TICKET] Cleanup logs

.github/workflows/dev-cluster-check.yml
[MGDOBR-477](https://issues.redhat.com/browse/MGDOBR-477)
<details>
<summary>
</summary>
</details>
=> MGDOBR-477 Send notification email when Dev cluster CI fails

kustomize/startMinikubeDeployLocalDev.sh
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] Update startMinikubeDeployLocalDev script with minikube IP

.github/workflows/stable-cluster-check.yml
[MGDOBR-332](https://issues.redhat.com/browse/MGDOBR-332)
The stable environment should be continuously tested using our E2E tests.
- [*] Pull …
=> MGDOBR-332 - Continuous Testing of our Stable Environment

REPORT_PORTAL.md, actions/src/test/filtered-resources/reportportal.properties, build-parent/pom.xml, executor/pom.xml, executor/src/test/filtered-resources/reportportal.properties, executor/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, infra/pom.xml, infra/src/test/filtered-resources/reportportal.properties, infra/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, ingress/pom.xml, ingress/src/test/filtered-resources/reportportal.properties, ingress/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, manager/pom.xml, manager/src/test/filtered-resources/reportportal.properties, manager/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, pom.xml, processor/runtime/pom.xml, processor/runtime/src/test/filtered-resources/reportportal.properties, processor/runtime/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, rhoas-client/pom.xml, rhoas-client/src/test/filtered-resources/reportportal.properties, rhoas-client/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, shard-operator/pom.xml, shard-operator/src/test/filtered-resources/reportportal.properties, shard-operator/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
[MGDOBR-527](https://issues.redhat.com/browse/MGDOBR-527)
I followed the instructions written here: https://github.com/reportportal/agent-java-junit5 . Integration for Cucumber tests will follow.
- [*] Pull Request contains …
=> MGDOBR-527 - Report Portal integration for Junit 5 tests

.github/workflows/Operator-CI.yaml, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorService.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressService.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeIngressController.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorControllerTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeIngressControllerTest.java
[MGDOBR-589](https://issues.redhat.com/browse/MGDOBR-589)
<details>
<summary>
</summary>
</details>
=> MGDOBR-589: upgrade ingress/executor to a new image when available

build-parent/pom.xml, executor/pom.xml, executor/src/main/resources/application.properties, executor/src/test/resources/application.properties, infra/pom.xml, infra/src/main/java/com/redhat/service/smartevents/infra/models/dto/BridgeDTO.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/dto/ProcessorDTO.java, infra/src/main/resources/application.properties, ingress/pom.xml, ingress/src/main/resources/application.properties, manager/src/main/resources/application.properties, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/utils/Constants.java, shard-operator/src/main/resources/templates/bridge-executor-deployment.yaml, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-129](https://issues.redhat.com/browse/MGDOBR-129)
<details>
<summary>
</summary>
</details>
=> MGDOBR-129: Log in JSON (or other structured) format

manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceConnectorTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/TestConstants.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java
[MGDOBR-322](https://issues.redhat.com/browse/MGDOBR-322)
**Blocked by #646**
This PR belongs to the [Event Sources epic](https://issues.redhat.com/browse/MGDOBR-270) and is part of a sequence of PRs derived from the Event Sources PoC (#629)
The existing `ProcessorServiceTest` was quite complex and was in fact performing two completely separated kind of tests:
- Test `ProcessorService` logic (as one would expect from the test name).
- Test the interaction between `ProcessorService` and Managed Connectors client APIs (which involves `ProcessorService` but also `ConnectorService` and `ConnectorWorker`).
This refactor splits these two sets of tests in two separate classes: `ProcessorServiceTest` and `ProcessorServiceConnectorTest`. This makes it easier to extend the test logic once _Source …
=> MGDOBR-322: refactor ProcessorServiceTest

integration-tests/pom.xml
<details>
<summary>
</summary>
</details>
=> [NO JIRA] E2E raise parallelism

integration-tests/README.md
[MGDOBR-525](https://issues.redhat.com/browse/MGDOBR-525)
<details>
<summary>
</summary>
</details>
=> MGDOBR-525 Adjust integration-tests readme file

processor/configuration/pom.xml, processor/core/pom.xml, processor/pom.xml, processor/runtime/pom.xml
<details>
<summary>
</summary>
</details>
=> Refactor maven project structure for processors

manager/src/main/resources/application.properties
[MGDOBR-633](https://issues.redhat.com/browse/MGDOBR-633)
<details>
<summary>
</summary>
</details>
=> MGDOBR-633 Increase RHOAS default timeout

.github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-608](https://issues.redhat.com/browse/MGDOBR-608)
Currently Github actions for cluster checks [1,2] are running tests with the main branch. However, it may happen that tests on main are not compatible with code currently running on clusters or there is some new functionality on main branch which is not available on clusters yet. Therefore it will be better to run tests from specific commit from [3,4].
[1] https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/.github/workflows/dev-cluster-check.yml
[2] https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/.github/workflows/stable-cluster-check.yml
[3] https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/kustomize/overlays/prod/kustomization.yaml#L7
[4] …
=> MGDOBR-608 - Refactor cluster checks to use kustomization tags

build-parent/pom.xml, integration-tests/pom.xml, integration-tests/src/test/filtered-resources/reportportal.properties, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/RunCucumberTest.java, shard-operator-integration-tests/pom.xml, shard-operator-integration-tests/src/test/filtered-resources/reportportal.properties, shard-operator-integration-tests/src/test/java/com/redhat/service/smartevents/shard/operator/cucumber/RunCucumberTest.java
[MGDOBR-527](https://issues.redhat.com/browse/MGDOBR-527)
- [*] Pull Request contains description of the issue
- [*] Pull Request does not include …
=> MGDOBR-527 - Report Portal integration for Cucumber tests

integration-tests/pom.xml
To address https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/644#discussion_r858609320
<details>
<summary>
</summary>
</details>
=> NO JIRA Add a reference for Keycloak credentials in tests

manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsApiClientImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/AbstractWorker.java, manager/src/test/java/com/redhat/service/smartevents/manager/connectors/ConnectorsApiClientTest.java
[https://issues.redhat.com/browse/MGDOBR-636](https://issues.redhat.com/browse/MGDOBR-636)
<details>
<summary>
</summary>
</details>
=> MGDOBR-636: MC: Return HTTP-410 [GONE] when deleted not HTTP-404 [NOT_FOUND]

kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/shard/patches/deploy-config.yaml
=> [56bf1] Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/ChronoUnitConverter.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WaitingSteps.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WebhookSiteSteps.java, integration-tests/src/test/resources/features/processor-filter.feature
[MGDOBR-547](https://issues.redhat.com/browse/MGDOBR-547)
<details>
<summary>
</summary>
</details>
=> MGDOBR-547 Add E2E test for Processor Filter Update

integration-tests/pom.xml, shard-operator-integration-tests/pom.xml
- https://issues.redhat.com/browse/MGDOBR-497
<details>
<summary>
</summary>
</details>
=> MGDOBR-497: Exclude RunCucumberTest from sonar analysis

kustomize/overlays/stable/observability/kustomization.yaml
<details>
<summary>
</summary>
</details>
=> fix stable kustomization typo

dev/README.md, dev/bin/configure.sh, dev/bin/localconfig-example, dev/bin/manager-run.sh, kustomize/startMinikubeDeployLocalDev.sh
NO-JIRA
<details>
<summary>
</summary>
</details>
=> Rename OPENSHIFT_OFFLINE_TOKEN to MANAGED_CONNECTORS_AUTH_OFFLINE_TOKEN

infra/src/main/java/com/redhat/service/smartevents/infra/models/filters/BaseFilter.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/filters/StringBeginsWith.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/filters/StringContains.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/filters/StringEquals.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/filters/ValuesIn.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/gateways/Gateway.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-638](https://issues.redhat.com/browse/MGDOBR-638)
<details>
<summary>
</summary>
</details>
=> MGDOBR-638: Processor Status is showing as Provisioning upon updating the same as existing filter payload

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/BridgeUtils.java
Addressing the comment from PR review: https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/697#discussion_r862590118
[MGDOBR-645](https://issues.redhat.com/browse/MGDOBR-645)
- [*] The layers in the `kustomize` folder have been updated accordingly.
- [*] Pull …
=> MGDOBR-645 - Check also that OB_TOKEN is not empty

.github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-647](https://issues.redhat.com/browse/MGDOBR-647)
<details>
<summary>
</summary>
</details>
=> MGDOBR-647 Fix git commit resolving in dev and stable cluster CI

.github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-647](https://issues.redhat.com/browse/MGDOBR-647)
<details>
<summary>
</summary>
</details>
=> MGDOBR-647 Re-checkout proper branch in dev and stable cluster CI

infra/pom.xml, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorListResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/BridgeError.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/BridgeListResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorListResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ErrorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ProcessorsAPI.java, openapi/openapi.yaml
- https://issues.redhat.com/browse/MGDOBR-471
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/36
<details>
<summary>
</summary>
</details>
=> MGDOBR-471: Adjust OpenApi annotations to use ref instead of inline schema

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-650](https://issues.redhat.com/browse/MGDOBR-650)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-650] Update Variables Names in Openshift Template

.github/pull_request_template.md, .github/scripts/rebase-and-deploy-to-env.sh, .github/workflows/deploy-bot.yml
[MGDOBR-679](https://issues.redhat.com/browse/MGDOBR-679)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-679] Add deployer bot

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [35f8a] Update kustomization images

.github/scripts/rebase-and-deploy-to-env.sh
https://issues.redhat.com/browse/MGDOBR-684
<details>
<summary>
</summary>
</details>
=> MGDOBR-684 Update rebase-and-deploy-to-env.sh

.github/scripts/rebase-and-deploy-to-env.sh
[MGDOBR-685](https://issues.redhat.com/browse/MGDOBR-685)
<details>
<summary>
</summary>
</details>
=> MGDOBR-685 Redirect stdout to stderr to show the logs in the deployer bot

infra/src/main/java/com/redhat/service/smartevents/infra/models/dto/ManagedResourceStatus.java, integration-tests/src/test/resources/features/bridge.feature, integration-tests/src/test/resources/features/processor.feature, manager/src/main/java/com/redhat/service/smartevents/manager/models/Bridge.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Processor.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/AbstractWorker.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorker.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorker.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/ProcessorWorker.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/internal/ShardBridgesSyncAPITest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/BridgeDAOTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorkerTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorkerTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/ProcessorWorkerTest.java, openapi/openapi.yaml, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/TestSupport.java
[https://issues.redhat.com/browse/MGDOBR-455](https://issues.redhat.com/browse/MGDOBR-455)
<details>
<summary>
</summary>
</details>
=> MGDOBR-455: Introduce the "preparing" status for Bridges and Processors

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [052cb] Update kustomization images

kustomize/README.md
[MGDOBR-688](https://issues.redhat.com/browse/MGDOBR-688)
<details>
<summary>
</summary>
</details>
=> MGDOBR-688 Update deployer bot instructions

infra/src/main/java/com/redhat/service/smartevents/infra/models/connectors/ConnectorType.java
[MGDOBR-595](https://issues.redhat.com/browse/MGDOBR-595)
Follows #638 
<details>
<summary>
</summary>
</details>
=> MGDOBR-595: fix ConnectorType for openapi

integration-tests/src/test/resources/features/processor-filter.feature
[MGDOBR-346](https://issues.redhat.com/browse/MGDOBR-346)
<details>
<summary>
</summary>
</details>
=> MGDOBR-346: Filter check for message matching or not

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [d80ee] Update kustomization images

infra/src/main/java/com/redhat/service/smartevents/infra/models/connectors/ConnectorType.java, infra/src/main/java/com/redhat/service/smartevents/infra/models/processors/ProcessorType.java, openapi/openapi.yaml
[MGDOBR-595](https://issues.redhat.com/browse/MGDOBR-595)
Follows #638 and #726 
<details>
<summary>
</summary>
</details>
=> MGDOBR-595: fix ProcessorType for openapi

shard-operator/pom.xml
Jira : https://issues.redhat.com/browse/MGDOBR-693
This profile is require in CPaas onboarding to create operator bundle
<details>
<summary>
</summary>
</details>
=> [MGDOBR-693] : Add attach-kubernetes-resources profile

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [032a9] Update kustomization images

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-700](https://issues.redhat.com/browse/MGDOBR-700)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-700] - adding fleet manager vault secret

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-700](https://issues.redhat.com/browse/MGDOBR-700)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-700] - Add Vault Parameters to Template

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteResource.java
[MGDOBR-716](https://issues.redhat.com/browse/MGDOBR-716)
<details>
<summary>
</summary>
</details>
=> MGDOBR-716 Fix Webhook site requests to query latest messages

processor/configuration/src/main/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceConnector.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceResolver.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceValidator.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/GatewayConfiguratorImplTest.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceConnectorTest.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceResolverTest.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSourceValidatorTest.java, processor/core/src/main/java/com/redhat/service/smartevents/processor/sources/aws/AwsSqsSource.java
[MGDOBR-711](https://issues.redhat.com/browse/MGDOBR-711)
Add event source for [AWS SQS](https://aws.amazon.com/sqs/) that relies on [aws_sqs_source_0.1 managed connector](https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/blob/main/cos-fleet-catalog-connectors/aws/aws-sqs-0.1/src/generated/resources/connectors/aws_sqs_source_0.1.json).
```json
"source": {
"type": "AwsSqs",
"parameters": {
"aws_queue_url": "https://sqs.us-east-1.amazonaws.com/123456789012/example_queue",
"aws_access_key_id": "<my_access_key_id>",
"aws_secret_access_key": "<my_secret_access_key>",
}
}
```
```json
"source": {
"type": "AwsSqs",
"parameters": {
"aws_queue_url": "http://localhost:4566/000000000000/example_queue",
"aws_access_key_id": "test",
"aws_secret_access_key": "test",
}
}
```
Please make …
=> MGDOBR-711: Implement event source for AWS SQS

dev/bin/localconfig-example
NO_JIRA
<details>
<summary>
</summary>
</details>
=> Add EVENT_BRIDGE_RESOURCE_PREFIX into localconfig-example

.github/workflows/CI.yaml
NO JIRA.. See https://chat.google.com/room/AAAAS9_noiE/234KFBTzal8
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Add fetch-depth for checkouts during CI.

integration-tests/README.md, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/UuidResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/SlackResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ProcessorSteps.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/SlackSteps.java, integration-tests/src/test/resources/features/source-slack.feature
The added test cratues two processors
- Slack Source processor - observing slack channel and recreating new cloud event
- Slack Action/Sink processor - takes cloud event of ^ and resend new message to slack channel
The first slack message is created via slack webhook url
```
And create message with text "Slack Event Source Feature trigger" on slack channel
```
The new generated message is checked as
```
Then Slack channel contains message with text "Message Slack Event Source Feature trigger was observed" within 1 minute
```
**Question**
The message on slack should contain some timestamp or other identiefier to be the message always unique? In other words so we are usre we didn't read old message from slack?
[MGDOBR-646](https://issues.redhat.com/browse/MGDOBR-646)
Please make sure that …
=> MGDOBR-646: Slack Event Sources Integration test

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteQuerySorting.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WebhookSiteSteps.java
[MGDOBR-722](https://issues.redhat.com/browse/MGDOBR-722)
<details>
<summary>
</summary>
</details>
=> MGDOBR-722 : Adjust tests to delete Webhook site history

dev/bin/interaction/delete-test-resources.sh
<details>
<summary>
</summary>
</details>
=> NO JIRA Add a script to delete Bridges and Processors created by E2E

processor/configuration/src/main/resources/application.properties, processor/configuration/src/test/resources/application.properties
[https://issues.redhat.com/browse/MGDOBR-738](https://issues.redhat.com/browse/MGDOBR-738)
<details>
<summary>
</summary>
</details>
=> MGDOBR-738: MC do not support processors as part of Service Preview

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [22c35] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [f0373] Update kustomization images

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-219](https://issues.redhat.com/browse/MGDOBR-219)
<details>
<summary>
</summary>
</details>
=> MGDOBR-219 - Enforce SSL Connections from Fleet Manager to Database

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [ad06f] Update kustomization images

shard-operator/src/main/resources/application.properties
[MGDOBR-754](https://issues.redhat.com/browse/MGDOBR-754)
<details>
<summary>
</summary>
</details>
=> MGDOBR-754: add default value for auth server url

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [cda4d] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml, kustomize/base/shard/resources/bridgeingresses.com.redhat.service.bridge-v1.yml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [12033] Update kustomization images

.github/workflows/openapi_update.yaml
Hi
I'm working on POC for adding automatic discovery for your OpenAPI changes for the purpose of generating SDKs.
This PR is all we need to have along with the secret value that we need to set up.
I will share the details in a separate email.
=> fix: automation for openAPI updates

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-237](https://issues.redhat.com/browse/MGDOBR-237)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-237] - Forward Fleet Manager Logs to centralised Logging Store

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [2ca07] Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/SlackSteps.java
[MGDOBR-761](https://issues.redhat.com/browse/MGDOBR-761)
<details>
<summary>
</summary>
</details>
=> MGDOBR-761 Increase the Slack messages polling interval in tests

build-parent/pom.xml
[MGDOBR-768](https://issues.redhat.com/browse/MGDOBR-768)
<details>
<summary>
</summary>
</details>
=> MGDOBR-768: Upgrade jacoco maven plugin 0.8.8

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [206eb] Update kustomization images

app-interface/dashboards/grafana-dashboard-rhose-fleet-manager.configmap.yaml
[MGDOBR-570](https://issues.redhat.com/browse/MGDOBR-570)
<details>
<summary>
</summary>
</details>
=> add rhose grafana dashboard

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [b298a] Update kustomization images

.github/workflows/dev-cluster-check.yml, .github/workflows/dev-cluster-long-running-bridge.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-776](https://issues.redhat.com/browse/MGDOBR-776)
<details>
<summary>
</summary>
</details>
=> MGDOBR-776 Remove google chat cotification

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [e566a] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [501c5] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [9e732] Update kustomization images

manager/src/test/java/com/redhat/service/smartevents/manager/api/user/SchemaAPITest.java
[MGDOBR-766](https://issues.redhat.com/browse/MGDOBR-766)
<details>
<summary>
</summary>
</details>
=> MGDOBR-766 Fix test condition to check required or optional elements

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ProcessorSteps.java
[MGDOBR-695](https://issues.redhat.com/browse/MGDOBR-695)
<details>
<summary>
</summary>
</details>
=> MGDOBR-695 Waiting loops Failchecks

.github/workflows/dev-cluster-check.yml
[MGDOBR-783](https://issues.redhat.com/browse/MGDOBR-783)
<details>
<summary>
</summary>
</details>
=> MGDOBR-783 configure sheriff details on dev cluster CI failure email

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [866e7] Update kustomization images

executor/src/main/resources/application.properties
[MGDOBR-144](https://issues.redhat.com/browse/MGDOBR-144)
<details>
<summary>
</summary>
</details>
=> MGDOBR-144: use 'ignore' as default failure strategy

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [177ce] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [27b97] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [9db1b] Update kustomization images

.github/data/sheriff-order, .github/scripts/sheriff-queue.sh
[MGDOBR-831](https://issues.redhat.com/browse/MGDOBR-831)
<details>
<summary>
</summary>
</details>
=> MGDOBR-831 Adjusting logic to count the last sheriff for the CI failure

manager/src/main/java/com/redhat/service/smartevents/manager/dao/ProcessorDAO.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Processor.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java
[https://issues.redhat.com/browse/MGDOBR-755](https://issues.redhat.com/browse/MGDOBR-755)
<details>
<summary>
</summary>
</details>
=> MGDOBR-755: Processors default sorting of GET /bridges/{bridgeId}/processors/{processorId}

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [fe9ff] Update kustomization images

manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorSchemaEntryResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/SchemaAPI.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/SchemaAPITest.java, openapi/rhose-api.yaml, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/ProcessorCatalogService.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/ProcessorCatalogServiceImpl.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/models/ProcessorCatalogEntry.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/validators/AbstractGatewayValidator.java, processor/configuration/src/main/resources/schemas/actions/catalog.json, processor/configuration/src/main/resources/schemas/sources/catalog.json
[MGDOBR-791](https://issues.redhat.com/browse/MGDOBR-791)
<details>
<summary>
</summary>
</details>
=> MGDOBR-791: add name/description to processor catalog

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [8c0ae] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [d1011] Update kustomization images

.github/workflows/Operator-CI.yaml
In order to make the Operator CI work with knative https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/586 we need those changes
<details>
<summary>
</summary>
</details>
=> prepare operator CI for knative

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [5ab25] Update kustomization images

.github/workflows/Manager-CI.yaml
<details>
<summary>
</summary>
</details>
=> Prepare managerCI for knative

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/SlackResource.java
- https://api.slack.com/methods/conversations.history
<details>
<summary>
</summary>
</details>
=> [no-jira]  Read slack messages history no older than one day

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [7753f] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [f2b55] Update kustomization images

manager/src/main/java/com/redhat/service/smartevents/manager/api/models/requests/BridgeRequest.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/requests/ProcessorRequest.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorRequestForTests.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ProcessorAPITest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/validators/processors/ProcessorGatewayConstraintValidatorTest.java
[https://issues.redhat.com/browse/MGDOBR-721](https://issues.redhat.com/browse/MGDOBR-721)
<details>
<summary>
</summary>
</details>
=> MGDOBR-721: ManagedResource: Validate and trim name

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [4393a] Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/SlackResource.java
[MGDOBR-864](https://issues.redhat.com/browse/MGDOBR-864)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-864] Resolving timezone issue while reading slack messages

docker/Dockerfile.appsre
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - add gzip on app-sre Dockerfile

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/AbstractManagerSyncServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/AbstractShardWireMockTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceMockedTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-769](https://issues.redhat.com/browse/MGDOBR-769)
<details>
<summary>
</summary>
</details>
=> MGDOBR-769: Bridge stuck in provisioning status

infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/definitions/platform/ConnectorUpdateException.java, manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsApiClient.java, manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsApiClientImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsService.java, manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/ManagedResource.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorker.java, manager/src/main/resources/db/migration/0.1/V0.1.15__add_generation.sql, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceConnectorTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/connectors/ConnectorsApiClientTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/connectors/ConnectorsServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-516](https://issues.redhat.com/browse/MGDOBR-516)
<details>
<summary>
</summary>
</details>
=> MGDOBR-516: Allow a user to update Action Parameters on a Sink Processor

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml, kustomize/base/shard/resources/bridgeingresses.com.redhat.service.bridge-v1.yml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [MGDOBR-536] Update kustomization images - knative replaces ingress

kustomize/base-openshift/shard/knative/broker-network-policy.yaml, kustomize/base-openshift/shard/knative/webhook-network-policy.yaml
Small fix for the knative work 
<details>
<summary>
</summary>
</details>
=> MGDOBR-536 - fix network policies for knative

processor/configuration/src/main/resources/schemas/actions/ansible_tower_job_template_sink_0.1.json, processor/configuration/src/main/resources/schemas/sources/aws_sqs_source_0.1.json
This PR is a follow up work for https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/79
The backend processor configuration schemas are crucial for UI forms generation. During review https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/79#pullrequestreview-1016493932 were identiefied backend configurations, that can be slightly updated, to obtain easier to use/read UI.
This PR address especially point 2) and 5) of review https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/79#pullrequestreview-1016493932.
[MGDOBR-848](https://issues.redhat.com/browse/MGDOBR-848)
<details>
<summary>
How to trigger pipelines and …
=> MGDOBR-848: Schema catalog enhancements

dev/bin/interaction/delete-managed-connectors.sh
[MGDOBR-804](https://issues.redhat.com/browse/MGDOBR-804)
<details>
<summary>
</summary>
</details>
=> MGDOBR-804 : Add script to delete managed connectors

manager/src/main/java/com/redhat/service/smartevents/manager/GatewayConfiguratorServiceImpl.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/GatewayConfiguratorService.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/InternalKafkaConnectionPayloadImpl.java, processor/configuration/src/main/java/com/redhat/service/smartevents/processor/resolvers/custom/KafkaTopicActionResolver.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/GatewayConfiguratorServiceMock.java, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/resolvers/custom/SlackActionResolverTest.java, processor/core/src/main/java/com/redhat/service/smartevents/processor/actions/kafkatopic/KafkaTopicAction.java, processor/runtime/src/main/java/com/redhat/service/smartevents/processor/actions/kafkatopic/KafkaOutboundClients.java
<details>
<summary>
</summary>
</details>
=> MGDOBR-892: Remove dlq for outbound kafka action

manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-914](https://issues.redhat.com/browse/MGDOBR-914)
<details>
<summary>
</summary>
</details>
=> MGDOBR-914: Unable to list Processors for a FAILED Bridge

infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorsResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/definitions/platform/UnclassifiedException.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/mappers/ConstraintViolationExceptionMapper.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/mappers/ExternalUserExceptionMapper.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/mappers/InternalPlatformExceptionMapper.java, infra/src/main/resources/exception/exceptionInfo.json, infra/src/test/java/com/redhat/service/smartevents/infra/exceptions/mappers/ConstraintViolationExceptionMapperTest.java, infra/src/test/java/com/redhat/service/smartevents/infra/exceptions/mappers/ExternalUserExceptionMapperTest.java, infra/src/test/java/com/redhat/service/smartevents/infra/exceptions/mappers/InternalPlatformExceptionMapperTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java
[https://issues.redhat.com/browse/MGDOBR-897](https://issues.redhat.com/browse/MGDOBR-897)
<details>
<summary>
</summary>
</details>
=> MGDOBR-897: Public API to return ErrorsResponse

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/SlackResource.java, manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/dao/WorkDAO.java, manager/src/main/java/com/redhat/service/smartevents/manager/metrics/MetricsServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Work.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/WorkManagerImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/AbstractWorker.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/BridgeDAOTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/metrics/MetricsServiceImplTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/utils/Fixtures.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/AbstractWorkerTest.java
[[Insert JIRA Issue number and update link](https://issues.redhat.com/browse/MGDOBR-)
](https://issues.redhat.com/browse/MGDOBR-915)
<details>
<summary>
</summary>
</details>
=> MGDOBR-915: use datetime in UTC

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [1d4a2] Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [0cf58] Update kustomization images

kustomize/overlays/minikube/manager/kustomization.yaml, kustomize/overlays/minikube/manager/patches/deploy.yaml, manager/pom.xml
[MGDOBR-924](https://issues.redhat.com/browse/MGDOBR-924)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-924] Raise failureThreshold to 10 for minikube environment

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] update number of replicas to 1

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - Increasing fleet manager resources

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA] - Update log level to INFO

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [0a376] Update kustomization images

integration-tests/README.md, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/RunPerformanceCucumberTest.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/Utils.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/BridgeEndpointBaseResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/BridgeEndpointPathResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ManagerAuthenticationTokenResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/PerformanceResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/performance/WebhookPerformanceResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/cloud-events-performance.feature
[MGDOBR-875](https://issues.redhat.com/browse/MGDOBR-875)
<details>
<summary>
</summary>
</details>
=> MGDOBR-875 - Cloud events performance testing for RHOSE

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
=> [2d81c] Update kustomization images

.github/actions/e2e-test-config/action.yml, .github/e2e-test-config.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-803](https://issues.redhat.com/browse/MGDOBR-803)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-803] Configure GHA for E2E test migration to TNB

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/providers/IstioGatewayProviderImpl.java
[MGDOBR-940](https://issues.redhat.com/browse/MGDOBR-940)
<details>
<summary>
</summary>
</details>
=> MGDOBR-940: let the operator run even if it is broken

.github/actions/e2e-test-config/action.yml, .github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
<details>
<summary>
</summary>
</details>
=> [NO JIRA] GHA: Pass secret env variables to composite action

integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature
[MGDOBR-236](https://issues.redhat.com/browse/MGDOBR-236)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-236] Add perf scenario for creating multiple Bridges at once

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [bf769] Update kustomization images

.github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/dev-cluster-long-running-bridge.yml, .github/workflows/stable-cluster-check.yml
Also removing duplicit Slack env variables.
[MGDOBR-803](https://issues.redhat.com/browse/MGDOBR-803)
<details>
<summary>
</summary>
</details>
=> MGDOBR-803 Configure GHA for long running Bridge E2E test to TNB

infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/BaseResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ListResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/PagedListResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/BaseManagedResourceResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/BridgeResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/CloudProviderResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/CloudRegionResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorCatalogResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/ProcessorSchemaEntryResponse.java, openapi/smartevents_mgmt.yaml
[https://issues.redhat.com/browse/MGDOBR-683](https://issues.redhat.com/browse/MGDOBR-683)
<details>
<summary>
</summary>
</details>
=> MGDOBR-683: [UI] Generated TS SDK from OpenApi spec - wrongfully optional properties

processor/configuration/src/main/resources/schemas/sources/aws_sqs_source_0.1.json, processor/configuration/src/test/java/com/redhat/service/smartevents/processor/validators/DefaultGatewayValidatorTest.java
[MGDOBR-962](https://issues.redhat.com/browse/MGDOBR-962)
<details>
<summary>
</summary>
</details>
=> MGDOBR-962: remove regex from aws_queue_name_or_arn in AWS SQS source

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
=> [5dd46] Update kustomization images

.github/workflows/Manager-CI.yaml
Fix PR check parameters for Kafka integration test.
=> MGDOBR-306: Add missing paremeter to PR check

.github/workflows/openapi_validate.yaml, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/BaseResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorsResponse.java, infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/PagedListResponse.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/CloudProviderAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ErrorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ProcessorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/SchemaAPI.java, manager/src/main/resources/application.properties, openapi/smartevents_mgmt.yaml
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/894
- https://issues.redhat.com/browse/MGDOBR-843
<details>
<summary>
</summary>
</details>
=> MGDOBR-843 Fix spectral lint errors for rhose-api.yaml

kustomize/base-openshift/shard/cluster-role.yaml, shard-operator/src/main/kubernetes/minikube.yml, shard-operator/src/main/kubernetes/openshift.yml
https://issues.redhat.com/browse/MGDOBR-965
<details>
<summary>
</summary>
</details>
=> [MGDOBR-965] - Provide fixed resource/verb in RBAC

.github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-306](https://issues.redhat.com/browse/MGDOBR-306)
Update Github actions to contain parameters for Kafka action E2E test.
=> MGDOBR-306 - Prepare GH actions parameters for Kafka E2E test

README.md
Add the dev/stable cluster status badge on the readme so that consumers can see if the platform on such clusters is running fine
<details>
<summary>
</summary>
</details>
=> Add dev/stable status badge in readme

kustomize/base/manager/resources/deploy.yaml
[MGDOBR-233](https://issues.redhat.com/browse/MGDOBR-233) 
<details>
<summary>
</summary>
</details>
=> MGDOBR-233: deploy 2 manager replicas

kustomize/base/manager/resources/deploy.yaml
This reverts commit 4c228338fcbd0d075dcff7bb9236b8a271a1be48.
<details>
<summary>
</summary>
</details>
=> MGDOBR-233: deploy 2 manager replicas (#425) - Revert 

integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/KafkaTopicResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/kafka/KafkaConnectionParameters.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/kafka/KafkaResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/KafkaSteps.java, integration-tests/src/test/resources/features/action-kafka.feature
Replacement of PR: https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/956 which had to be reverted by connection timeouts of Kafka client.
=> MGDOBR-306 - Implement ittest for KafkaTopicAction

.github/workflows/Operator-CI.yaml
<details>
<summary>
</summary>
</details>
=> [NOJIRA] Fix operator CI

infra/src/main/java/com/redhat/service/smartevents/infra/api/models/responses/ErrorResponse.java, openapi/smartevents_mgmt.yaml
[https://issues.redhat.com/browse/MGDOBR-935](https://issues.redhat.com/browse/MGDOBR-935)
<details>
<summary>
</summary>
</details>
=> MGDOBR-935: smartevents_mgmt.yaml spectral lint validation

.github/workflows/Manager-CI.yaml
<details>
<summary>
</summary>
</details>
=> [NOJIRA] Manager-CI: deploy manager first and increase shard timeout

app-interface/manifests/rhose-fleet-manager.yml
…Template
[MGDOBR-838](https://issues.redhat.com/browse/MGDOBR-838)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-838] Added missing properties to the Fleet Manager Openshift Template

build-parent/pom.xml
https://issues.redhat.com/browse/MGDOBR-982
<details>
<summary>
</summary>
</details>
=> MGDOBR-982 - Revert back Quarkus version to 2.7.5.Final

manager/src/main/java/com/redhat/service/smartevents/manager/BridgesService.java, manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorService.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/requests/BridgeRequest.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ProcessorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/ManagedResource.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Processor.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorker.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgeRequestForTests.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/TestConstants.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/service/smartevents/manager/utils/TestUtils.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorkerTest.java, openapi/smartevents_mgmt.yaml, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceImpl.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-779](https://issues.redhat.com/browse/MGDOBR-779)
Following the virtual Face to Face the approach taken in this PR was considered suitable.
Details of the Bridge instance status will be available when [MGDOBR-52](https://issues.redhat.com/browse/MGDOBR-52) is completed.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> …
=> MGDOBR-779: Make BridgeInstance error handling strategy editable

manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java
[https://issues.redhat.com/browse/MGDOBR-975](https://issues.redhat.com/browse/MGDOBR-975)
<details>
<summary>
</summary>
</details>
=> MGDOBR-975: Error Handling: Check we can update type from Webhook to Kafka

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/BridgeResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/resources/features/error-handling.feature
[MGDOBR-888](https://issues.redhat.com/browse/MGDOBR-888)
Note: Waiting for PR https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/875 to merge
<details>
<summary>
</summary>
</details>
=> [MGDOBR-888] Add E2E test for bridge Error Handler update

shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-991](https://issues.redhat.com/browse/MGDOBR-991)
<details>
<summary>
</summary>
</details>
=> MGDOBR-991: BridgeIngressServiceTest/BridgeExecutorServiceTest: Disable failing tests

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-975: Error Handling: Check we can update type from Webhook to Kafka (#1017)
=> MGDOBR-975: Error Handling: Check we can update type from Webhook to Kafka (#1017) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-991: BridgeIngressServiceTest/BridgeExecutorServiceTest: Disable failing tests (#1025)
=> MGDOBR-991: BridgeIngressServiceTest/BridgeExecutorServiceTest: Disable failing tests (#1025) - Update kustomization images

integration-tests/src/test/resources/performance-features/cloud-events-performance.feature, integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Apply cloud provider and region for perf tests

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/base/shard/resources/bridgeingresses.com.redhat.service.bridge-v1.yml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-951: shard exposes applications with the host and the ssl certificates provided by the manager (#1006)
=> MGDOBR-951: shard exposes applications with the host and the ssl certificates provided by the manager (#1006) - Update kustomization images

.github/actions/e2e-test-config/action.yml, .github/e2e-test-config.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/dev-cluster-long-running-bridge.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-899](https://issues.redhat.com/browse/MGDOBR-899)
=> [MGDOBR-899] Configuration for new slackchannel details

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/IngressResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/IngressSteps.java
[MGDOBR-1001](https://issues.redhat.com/browse/MGDOBR-1001)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1001: Fix integration tests dns

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeIngressController.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/utils/AwaitilityUtil.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/utils/KubernetesResourcePatcher.java
[https://issues.redhat.com/browse/MGDOBR-992](https://issues.redhat.com/browse/MGDOBR-992)
<details>
<summary>
</summary>
</details>
=> MGDOBR-992: BridgeIngressServiceTest/BridgeExecutorServiceTest: Fix disabled tests

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-992: BridgeIngressServiceTest/BridgeExecutorServiceTest: Fix disabled tests (#1034)
=> MGDOBR-992: BridgeIngressServiceTest/BridgeExecutorServiceTest: Fix disabled tests (#1034) - Update kustomization images

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceImpl.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java
[MGDOBR-989](https://issues.redhat.com/browse/MGDOBR-989)
<details>
<summary>
</summary>
</details>
=> MGDOBR-989 Update Bridge/Processor from Shard only for READY status

manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/models/responses/BaseManagedResourceResponse.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, openapi/smartevents_mgmt.yaml
[https://issues.redhat.com/browse/MGDOBR-1000](https://issues.redhat.com/browse/MGDOBR-1000)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1000: Bridge/Processor: Expose modifiedAt to the UI

integration-tests/README.md, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/Constants.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/EndPointParser.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/PerfTestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/performance/WebhookPerformanceResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/send-cloud-events.feature
[MGDOBR-875](https://issues.redhat.com/browse/MGDOBR-875)
Depends on https://github.com/afalhambra/webhook-perf-test/pull/1
<details>
<summary>
</summary>
</details>
=> [MGDOBR-875] - Adding submitted and received time check to the perf test along with some minor adjustments

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/minikube/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1000: Bridge/Processor: Expose modifiedAt to the UI (#1033)
=> MGDOBR-1000: Bridge/Processor: Expose modifiedAt to the UI (#1033) - Update kustomization images

.github/workflows/openapi_validate.yaml
Updating the OpenAPI Linter to the newest version in the CI. 
<details>
<summary>
</summary>
</details>
=> build: updating the rhoas guidelines to the newest version

manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java, manager/src/main/java/com/redhat/service/smartevents/manager/dao/ProcessorDAO.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Bridge.java, manager/src/main/java/com/redhat/service/smartevents/manager/models/Processor.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceConnectorTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/BridgeDAOTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java
[https://issues.redhat.com/browse/MGDOBR-456](https://issues.redhat.com/browse/MGDOBR-456)
<details>
<summary>
</summary>
</details>
=> MGDOBR-456: Improve names of BridgeDAO#findByShardIdWithReadyDependencies and ProcessorDAO#findByShardIdWithReadyDependencies

integration-tests/localconfig-example.properties, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WebhookSiteSteps.java, integration-tests/src/test/resources/features/action-webhook.feature, integration-tests/src/test/resources/features/error-handling.feature, integration-tests/src/test/resources/features/processor-filter.feature
[MGDOBR-860](https://issues.redhat.com/browse/MGDOBR-860)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-860] Tests for updated webhook processor parameters

.github/workflows/dev-cluster-long-running-bridge.yml
[MGDOBR-860](https://issues.redhat.com/browse/MGDOBR-860)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-860] CI check failure - Webhook id second added

app-interface/dashboards/grafana-dashboard-rhose-fleet-manager.-slosconfigmap.yaml
[MGDOBR-570](https://issues.redhat.com/browse/MGDOBR-570)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-570] - Create Dashboard for SLI/SLO Monitoring

build-parent/pom.xml, integration-tests/pom.xml, integration-tests/run-local-tests.sh, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/PerfTestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature
[MGDOBR-997](https://issues.redhat.com/browse/MGDOBR-997)
<details>
<summary>
</summary>
</details>
=> MGDOBR-997 E2E tests: Migrate Hyperfoil resources to TNB

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/minikube/kustomization.yaml, kustomize/overlays/minikube/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-836: mask sensitive parameters in RHOSE user APIs (#863)
=> MGDOBR-836: mask sensitive parameters in RHOSE user APIs (#863) - Update kustomization images

manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java
[https://issues.redhat.com/browse/MGDOBR-984](https://issues.redhat.com/browse/MGDOBR-984)
Further to https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/123 this PR adds some tests to the backend to demonstrate how the real backend operates (rightly or wrongly, that is the subject of https://issues.redhat.com/browse/MGDOBR-947)
<details>
<summary>
</summary> …
=> MGDOBR-984: Add Error Handling configuration to the bridge creation. Unit Tests to demonstrate backend behaviour.

manager/src/main/java/com/redhat/service/smartevents/manager/BridgesService.java, manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorService.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/utils/TestUtils.java
[https://issues.redhat.com/browse/MGDOBR-456](https://issues.redhat.com/browse/MGDOBR-456)
Further to #1043 this includes some additional methods missed the first time.
<details>
<summary>
</summary>
</details>
=> MGDOBR-456: Improve names of BridgeDAO#findByShardIdWithReadyDependencies and ProcessorDAO#findByShardIdWithReadyDependencies. More methods.

.github/workflows/Operator-CI.yaml, shard-operator/pom.xml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1004 : remove minikube profile references

build-parent/pom.xml, integration-tests/localconfig-example.yaml, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HorreumResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature, integration-tests/src/test/resources/performance-features/send-cloud-events.feature
[MGDOBR-1023](https://issues.redhat.com/browse/MGDOBR-1023)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1023 Upload performance test results to Horreum

.github/workflows/Operator-CI.yaml
<details>
<summary>
</summary>
</details>
=> [NO JIRA] fix operator CI

app-interface/dashboards/grafana-dashboard-rhose-fleet-manager-slos.configmap.yaml
[MGDOBR-1053](https://issues.redhat.com/browse/MGDOBR-1053)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1053] Update grafana-dashboard-rhose-fleet-manager-slos.configmap.yaml

.github/workflows/Operator-CI.yaml, shard-operator/README.md
<details>
<summary>
</summary>
</details>
=> retrigger tests

.github/workflows/Operator-CI.yaml, README.md, shard-operator/README.md
<details>
<summary>
</summary>
</details>
=> Mgdobr 1036 2

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> [NO-JIRA]- update fleet manager template to have 3 replicas

.github/workflows/Manager-CI.yaml, kustomize/overlays/ci/shard/cluster-role-binding.yaml, kustomize/overlays/ci/shard/cluster-role.yaml, kustomize/overlays/ci/shard/kustomization.yaml, manager/src/main/resources/application.properties
<details>
<summary>
</summary>
</details>
=> retrigger manager tests

manager/src/main/java/com/redhat/service/smartevents/processingerrors/api/models/ProcessingErrorResponse.java, openapi/smartevents_mgmt.yaml
[MGDOBR-1067](https://issues.redhat.com/browse/MGDOBR-1067)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1067: update ProcessingErrorResponse openapi

manager/src/main/java/com/redhat/service/smartevents/manager/BridgesServiceImpl.java, manager/src/test/resources/application.properties
[MGDOBR-1068](https://issues.redhat.com/browse/MGDOBR-1068)
Store the tls key and certificate as b64 on AWS sm and decode them in the manager. This is the only way I found to fix the encoding problem with AWS sm and external secret operator. 
<details>
<summary>
</summary> …
=> MGDOBR-1068: Fix tls encoding

.github/workflows/Manager-CI.yaml
[MGDOBR-1072](https://issues.redhat.com/browse/MGDOBR-1072)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1072: fix typo in pipeline

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml, shard-operator/pom.xml
<details>
<summary>
</summary>
</details>
=> Bump knative 1.2 - Update kustomization images

.github/workflows/Manager-CI.yaml, kustomize/overlays/ci/manager/cluster-secret-store.yaml, kustomize/overlays/ci/manager/kustomization.yaml, kustomize/overlays/ci/shard/awssm-secret.yaml, kustomize/overlays/ci/shard/cluster-secret-store.yaml, kustomize/overlays/ci/shard/kustomization.yaml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1072: fix pipeline

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeIngressController.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/BridgeExecutorStatus.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/BridgeIngressStatus.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/ConditionReasonConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/ConditionTypeConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/CustomResourceStatus.java, shard-operator/src/main/resources/application.properties, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeIngressServiceTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorControllerTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeIngressControllerTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/resources/CustomResourceStatusTest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/resources/FooResourceStatus.java, shard-operator/src/test/resources/application.properties
[https://issues.redhat.com/browse/MGDOBR-1035](https://issues.redhat.com/browse/MGDOBR-1035)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1035: Shard does not report Bridge as Failed if Knative Broker resource does not deploy

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-794: Add azure event hubs action (#824)
=> MGDOBR-794: Add azure event hubs action (#824) - Update kustomization images

build-parent/pom.xml
[MGDOBR-537](https://issues.redhat.com/browse/MGDOBR-537)
<details>
<summary>
</summary>
</details>
=> MGDOBR-537: Code coverage using jacoco

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-851: retrieve hosted zone id programmatically  (#1141)
=> MGDOBR-851: retrieve hosted zone id programmatically  (#1141) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR  [MGDOBR-1081] Error polling endpoint should not be documented (it is optional) (#1144)
=>  [MGDOBR-1081] Error polling endpoint should not be documented (it is optional) (#1144) - Update kustomization images

.github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/stable-cluster-check.yml
[MGDOBR-833](https://issues.redhat.com/browse/MGDOBR-833)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-833] Enabling Slack source E2E test

.github/actions/e2e-test-config/action.yml, .github/e2e-test-config.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/dev-cluster-check.yml, .github/workflows/dev-cluster-long-running-bridge.yml, .github/workflows/stable-cluster-check.yml, build-parent/pom.xml, integration-tests/README.md, integration-tests/localconfig-example.yaml, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/AwsAccessKeyResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/AwsRegionResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/AwsSecretKeyResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/AwsSqsQueueNameResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ContextResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/resolver/ProcessorIdResolver.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/AwsAccount.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/AwsSqsResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteRequest.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/AwsSqsSteps.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WebhookSiteSteps.java, integration-tests/src/test/resources/features/error-handling.feature
[MGDOBR-889](https://issues.redhat.com/browse/MGDOBR-889)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-889] - Implement E2E test for managed connector DLQ

.github/workflows/CI-Topics-Cleanup.yml
Create scaffold to test CI Topics Clean up Github action.
=> MGDOBR-356 - Prepare to test CI Topics Clean up

.github/scripts/delete-kafka-ci-topics.sh, .github/workflows/CI-Topics-Cleanup.yml
[MGDOBR-356](https://issues.redhat.com/browse/MGDOBR-356)
Periodically delete old ci- Kafka topics.
=> MGDOBR-356: Github action for deleting of old CI topics

scripts/dependencies/README.md, scripts/dependencies/approve-ip-patch.json, scripts/dependencies/common_tools.sh, scripts/dependencies/install_dependencies.sh, scripts/dependencies/serverless/kustomization.yaml, scripts/dependencies/serverless/resources/broker-network-policy.yaml, scripts/dependencies/serverless/resources/knative-eventing.yaml, scripts/dependencies/serverless/resources/knative-kafka.yaml, scripts/dependencies/serverless/resources/webhook-network-policy.yaml, scripts/dependencies/serverless/serverlessSub.yaml, scripts/dependencies/servicemesh/kialiSub.yaml, scripts/dependencies/servicemesh/kustomization.yaml, scripts/dependencies/servicemesh/resources/istio-system-namespace.yaml, scripts/dependencies/servicemesh/resources/service-mesh-control-plane.yaml, scripts/dependencies/servicemesh/resources/service-mesh-member-roll.yaml, scripts/dependencies/servicemesh/serviceMeshSub.yaml, scripts/dependencies/servicemesh/tracingSub.yaml, scripts/dependencies/uninstall_dependencies.sh
[MGDOBR-816](https://issues.redhat.com/browse/MGDOBR-816)
<details>
<summary>
</summary>
</details>
=> MGDOBR-816: Add Data Plane dependencies installation scripts

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-851](https://issues.redhat.com/browse/MGDOBR-851)
<details>
<summary>
</summary>
</details>
=> MGDOBR-851: add dns secrets in app interface yaml

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-889] - Implement E2E test for managed connector DLQ (#1061)
=> [MGDOBR-889] - Implement E2E test for managed connector DLQ (#1061) - Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java
[MGDOBR-1082](https://issues.redhat.com/browse/MGDOBR-1082)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1082: E2E test fix for run-local script

build-parent/pom.xml, dev/bin/manager-run.sh, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/kafka/KafkaConnectionParameters.java, manager/pom.xml, test-utils/src/main/java/com/redhat/service/smartevents/test/rhoas/KafkaInstanceAdminMockServerConfigurator.java, test-utils/src/main/java/com/redhat/service/smartevents/test/rhoas/testprofiles/RhoasTestProfile.java, test-utils/src/main/java/com/redhat/service/smartevents/test/rhoas/testprofiles/RhoasWithMissingMgmtApiPropsTestProfile.java
[MGDOBR-531](https://issues.redhat.com/browse/MGDOBR-531)
<details>
<summary>
</summary>
</details>
=> MGDOBR-531 Update Kafka and Connector SDK to latest version

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-531] Update Kafka and Connector SDK to latest version
=> [MGDOBR-531] Update Kafka and Connector SDK to latest version - Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/BridgeUtils.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/EndPointParser.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/BridgeResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/BridgeSteps.java, integration-tests/src/test/resources/features/error-handling.feature
[MGDOBR-1088](https://issues.redhat.com/browse/MGDOBR-1088)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1088] E2E testing for poll based error handling strategy

integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/Constants.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/MetricsConverter.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HorreumResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/ManagerResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/continuously-create-bridges.feature
[MGDOBR-746](https://issues.redhat.com/browse/MGDOBR-746)
<details>
<summary>
</summary>
</details>
=> MGDOBR-746 Test performance of Bridge creation and deletion

executor/src/main/java/com/redhat/service/smartevents/executor/MetricsConstants.java, infra/src/main/java/com/redhat/service/smartevents/infra/auth/OidcClientConstants.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/definitions/user/BadRequestException.java, infra/src/main/java/com/redhat/service/smartevents/infra/utils/Constants.java, manager/src/main/java/com/redhat/service/smartevents/manager/dns/KnativeBrokerPathBuilder.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/networking/NetworkingConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/providers/GlobalConfigurationsConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/ConditionReasonConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/ConditionTypeConstants.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/utils/Constants.java
[MGDOBR-1111](https://issues.redhat.com/browse/MGDOBR-1111)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1111 : Sonarcloud constructor issue

manager/src/main/resources/db/migration/0.1/V0.1.26__reset_data_plane_router_canonical_hostname.sql
[MGDOBR-1114](https://issues.redhat.com/browse/MGDOBR-1114)
This PR adds a database migration that simply re-applies the current configuration for the `router_canonical_hostname` field for the data plane configured in an environment. For the environment where the value is currently incorrect, this will update the environment to the correct value, whilst leaving other environments to re-use the existing configuration. This approach is required because:
- We don't yet have an API to manage data plane instances (captured in https://issues.redhat.com/browse/MGDOBR-1115)
- The environment in which it is incorrect, we have no direct write access to the DB and need to perform the update via a migration
*Run `mvn clean verify …
=> [MGDOBR-1114] Force a reset of the router_canonical_hostname to fix incorrect value in stage

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/IngressSteps.java
By catching DNS/SSL exceptions when checking that Bridge Ingress route works.
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Stabilize E2E Ingress step

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1114] Force a reset of the router_canonical_hostname field in environments to fix incorrect values (#1188)
=> [MGDOBR-1114] Force a reset of the router_canonical_hostname field in environments to fix incorrect values (#1188) - Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/src/test/resources/performance-features/continuously-create-bridges.feature, integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature, integration-tests/src/test/resources/performance-features/send-cloud-events.feature
<details>
<summary>
</summary>
</details>
=> NO JIRA Perf tests - run scenario when it is created

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-1126](https://issues.redhat.com/browse/MGDOBR-1126)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1126] Added the resource prefix property to the Openshift Template

kustomize/overlays/prod/awssm-secret.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/namespace.yaml, kustomize/overlays/prod/patch-with-istio-system-namespace.yaml, kustomize/overlays/prod/patch-with-knative-eventing-namespace.yaml, kustomize/overlays/prod/patches/deploy-config.yaml, kustomize/overlays/prod/secrets/addon-smart-events-operator-parameters.yaml, kustomize/overlays/prod/secrets/cluster-secret-store.yaml, kustomize/overlays/prod/secrets/kustomization.yaml, kustomize/overlays/prod/shard/cluster-role-binding.yaml, kustomize/overlays/prod/shard/kustomization.yaml
[Create new Kustomize overlay for Production Data Plane](https://issues.redhat.com/browse/MGDOBR-1069)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1069] Create new Kustomize overlay for Production Data Plane

.github/scripts/delete-webhook-requests.sh, .github/workflows/Webhook-Cleanup.yml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java
[MGDOBR-834](https://issues.redhat.com/browse/MGDOBR-834)
<details>
<summary>
</summary>
</details>
=> MGDOBR-834 Migrate Webhook cleanup to separate GHA

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1122] Used in-memory scheduler for OIDC token refresh (#1196)
=> [MGDOBR-1122] Used in-memory scheduler for OIDC token refresh (#1196) - Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/AwsSqsResource.java, integration-tests/src/test/resources/features/error-handling.feature
[MGDOBR-889](https://issues.redhat.com/browse/MGDOBR-889)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-889] - Fix for "Implement E2E test for managed connector DLQ" regarding AWS SQS setup

infra/src/main/java/com/redhat/service/smartevents/infra/auth/AbstractOidcClient.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorker.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/resources/CustomResourceStatus.java
[MGDOBR-1111](https://issues.redhat.com/browse/MGDOBR-1111)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1111 : Sonarcloud access modifier fix

.github/workflows/stage-cluster-check.yml
[MGDOBR-1140](https://issues.redhat.com/browse/MGDOBR-1140)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1140 Implement stage environment E2E test CI check

.github/workflows/production-cluster-check.yml
[MGDOBR-1145](https://issues.redhat.com/browse/MGDOBR-1145)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1145 Implement production environment E2E test CI check

app-interface/manifests/rhose-fleet-manager.yml
<details>
<summary>
</summary>
</details>
=> Add EVENT_BRIDGE_MANAGER_URL to openshift template

dev/bin/shard-run.sh, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/BridgeErrorHelper.java, infra/src/main/java/com/redhat/service/smartevents/infra/exceptions/BridgeErrorInstance.java, infra/src/test/java/com/redhat/service/smartevents/infra/exceptions/BridgeErrorHelperTest.java, manager/src/main/java/com/redhat/service/smartevents/manager/ProcessorServiceImpl.java, manager/src/main/java/com/redhat/service/smartevents/manager/metrics/ManagedResourceOperationMapper.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/BridgeWorker.java, manager/src/main/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorker.java, manager/src/test/java/com/redhat/service/smartevents/manager/ProcessorServiceTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/metrics/ManagedResourceOperationMapperTest.java, manager/src/test/java/com/redhat/service/smartevents/manager/workers/resources/ConnectorWorkerTest.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceImpl.java, shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/controllers/BridgeExecutorController.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/BridgeExecutorServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-1093](https://issues.redhat.com/browse/MGDOBR-1093)
See JIRA for details.
<details>
<summary>
</summary>
</details>
=> MGDOBR-1093: Processor is not updating to Ready state from Failed state

.github/workflows/Upgrade-CI.yml, .gitignore, integration-tests/pom.xml, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/RunUpgradeTest.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/BridgeContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/ProcessorContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ContextSteps.java, integration-tests/src/test/resources/upgrade-features/upgrade.feature
[MGDOBR-1097](https://issues.redhat.com/browse/MGDOBR-1097)
Github workflow for upgrade check
- [*] Pull Request contains description of the issue
- …
=> MGDOBR-1097 - Implement github action for testing of RHOSE upgrade

.github/scripts/rebase-and-deploy-to-env.sh
[MGDOBR-1154](https://issues.redhat.com/browse/MGDOBR-1154)
A simple update to the deploy bot to support the `prod` branch for the internal service preview.
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1154] Add support for prod branch to the deploy bot

app-interface/dashboards/grafana-dashboard-rhose-processing-errors.yaml
[MGDOBR-1022](https://issues.redhat.com/browse/MGDOBR-1022)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1022: populate 'templating' list in app-interface processing error dashboard

infra/src/main/java/com/redhat/service/smartevents/infra/auth/AbstractOidcClient.java
[MGDOBR-1164](https://issues.redhat.com/browse/MGDOBR-1164)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1164: catch exception in oidcclient scheduler

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
… kustomization images
<details>
<summary>
</summary>
</details>
=> MGDOBR-1164: catch exception in oidcclient scheduler (#1242) - Update kustomization images

kustomize/base-openshift/shard/knative/kafka-webhook-eventing-policy.yaml, kustomize/base-openshift/shard/knative/kustomization.yaml, kustomize/overlays/dev/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/stable/kustomization.yaml
[MGDOBR-1170](https://issues.redhat.com/browse/MGDOBR-1170)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1170: add network policy for serverless 1.25

manager/pom.xml, manager/src/main/java/com/redhat/service/smartevents/manager/api/internal/ShardBridgesSyncAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/BridgesAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/CloudProviderAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ErrorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ProcessorsAPI.java, manager/src/main/java/com/redhat/service/smartevents/manager/api/user/SchemaAPI.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java, manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ProcessorAPITest.java, shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-1161](https://issues.redhat.com/browse/MGDOBR-1161)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1161: Add Microprofile @RegisterClientHeaders to REST API services

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1161: Add Microprofile @RegisterClientHeaders to REST API services (#1238)
=> MGDOBR-1161: Add Microprofile @RegisterClientHeaders to REST API services (#1238) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1139: add checks on organization quotas (#1245)
=> MGDOBR-1139: add checks on organization quotas (#1245) - Update kustomization images

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java
[MGDOBR-1179](https://issues.redhat.com/browse/MGDOBR-1179)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1179 Performance tests: Store benchmark report as a file

app-interface/manifests/rhose-fleet-manager.yml
[MGDOBR-1139](https://issues.redhat.com/browse/MGDOBR-1139)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1139: Update app-interface template

manager/src/main/java/com/redhat/service/smartevents/processingerrors/api/ProcessingErrorsAPI.java, openapi/smartevents_mgmt.yaml
Remaining cleanup 
[MGDOBR-1081](https://issues.redhat.com/browse/MGDOBR-1081)
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1081] Leftover cleanup of processing errors OpenAPI

.github/workflows/dev-cluster-check.yml, .github/workflows/production-cluster-check.yml, .github/workflows/stable-cluster-check.yml, .github/workflows/stage-cluster-check.yml
[MGDOBR-1180](https://issues.redhat.com/browse/MGDOBR-1180)
Archive junit test results for E2E tests.
<details>
<summary>
</summary>
</details>
=> MGDOBR-1180 - Archive artifacts with junit test results

.github/workflows/dev-cluster-check.yml, .github/workflows/production-cluster-check.yml, .github/workflows/stable-cluster-check.yml, .github/workflows/stage-cluster-check.yml
Forgot to export junits also for failed runs.
=> MGDOBR-1180 - Always export junit artifacts

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1159]:Move all integration tests into a module
=> [MGDOBR-1159]:Move all integration tests into a module - Update kustomization images

.github/workflows/deploy-bot.yml
Deploy bot is broken I think due to the version bump  in https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1228 
<details>
<summary>
</summary>
</details>
=> MGDOBR-1206: Fix deploy-bot.yml

.github/workflows/deploy-bot.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for the correct usage 
<details>
<summary>
</summary>
</details>
=> MGDOBR-1206: Update deploy-bot.yml

.github/workflows/deploy-bot.yml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1206: Fix output variable in deploy-bot.yml

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1106: API versioning: Manager services and models (#1198)
=> MGDOBR-1106: API versioning: Manager services and models (#1198) - Update kustomization images

.github/workflows/CI.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, .github/workflows/Upgrade-CI.yml, .github/workflows/dev-cluster-check.yml, .github/workflows/dev-cluster-long-running-bridge.yml, .github/workflows/production-cluster-check.yml, .github/workflows/stable-cluster-check.yml, .github/workflows/stage-cluster-check.yml
Follow up for https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1262#discussion_r1011381808
=> [no Jira] Unify usage of conditionals in workflows

dev/bin/report-portal/report-portal-import-from-workflows.sh
Import test results from Github workflows to Report Portal.
=> MGDOBR-1180 - Script for test results import to Report Portal

.github/workflows/CD.yml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1207: Update CD.yml with the new module structure

executor/pom.xml, infra-parent/infra-core/pom.xml, infra-parent/infra-v1/pom.xml
[https://issues.redhat.com/browse/MGDOBR-1208](https://issues.redhat.com/browse/MGDOBR-1208)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1208: Review infra-xxx pom dependencies

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1208: Review infra-xxx pom dependencies (#1289)
=> MGDOBR-1208: Review infra-xxx pom dependencies (#1289) - Update kustomization images

dev/bin/manager-run.sh
<details>
<summary>
</summary>
</details>
=> Fix for manager-run.sh script

manager-parent/manager-core/pom.xml, manager-parent/manager-v1/pom.xml
[https://issues.redhat.com/browse/MGDOBR-1209](https://issues.redhat.com/browse/MGDOBR-1209)
Depends on #1289 [1]. I will rebase this PR after that one is merged.
[1] I didn't want to do the `manager` pom changes in parallel in case changes in `infra` affected it.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a …
=> MGDOBR-1209: Review manager-xxx pom dependencies

.github/workflows/perf-check.yml, integration-tests/manager-integration-tests/README.md, integration-tests/manager-integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/HyperfoilResource.java, integration-tests/manager-integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/Hooks.java, integration-tests/manager-integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/PerformanceSteps.java, integration-tests/manager-integration-tests/src/test/resources/performance-features/continuously-create-bridges.feature, integration-tests/manager-integration-tests/src/test/resources/performance-features/continuously-create-processors.feature, integration-tests/manager-integration-tests/src/test/resources/performance-features/create-bridges-at-once.feature, integration-tests/manager-integration-tests/src/test/resources/performance-features/send-cloud-events.feature
There are still some Horreum leftovers, I will remove them once a complete CI to upload to Horreum will be implemented.
[MGDOBR-1199](https://issues.redhat.com/browse/MGDOBR-1199)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1199 Run Performance tests on dev cluster

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1215: Manager: Remove manager-core test-jar usage (#1303)
=> MGDOBR-1215: Manager: Remove manager-core test-jar usage (#1303) - Update kustomization images

manager-parent/manager-v1/src/main/resources/db/migration/0.1/V0.1.5__create_shards.sql
[https://issues.redhat.com/browse/MGDOBR-1215](https://issues.redhat.com/browse/MGDOBR-1215)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1215: Revert SQL script to original formatting.

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1215: Revert SQL script to original formatting. (#1306)
=> MGDOBR-1215: Revert SQL script to original formatting. (#1306) - Update kustomization images

docker/Dockerfile.appsre
<details>
<summary>
</summary>
</details>
=> MGDOBR-1217: Update Dockerfile.appsre

build-parent/pom.xml, integration-tests/manager-integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/AwsAccount.java, integration-tests/manager-integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteAccount.java
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Upgrade TNB to latest version

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR
=> [NO-JIRA] Upgraded k8s version in minikube to 1.22.2 - Update kustomization images

dev/README.md, dev/bin/.gitignore, dev/bin/camel-k-installer.sh, dev/bin/configure.sh, dev/bin/minikube-start.sh
[MGDOBR-1221](https://issues.redhat.com/browse/MGDOBR-1221)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1221: install Camel K in Minikube for local dev

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/ProcessorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/requests/ProcessorRequest.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ProcessorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ProcessorResponse.java, openapi/smartevents_mgmt_v2.yaml
[MGDOBR-1211](https://issues.redhat.com/browse/MGDOBR-1211)
Add processor v2 api
<details>
<summary>
</summary>
</details>
=> MGDOBR-1211: add processors api V2

integration-tests/webhook-perf-test/pom.xml, integration-tests/webhook-perf-test/src/main/java/com/redhat/service/smartevents/WebhookResource.java, integration-tests/webhook-perf-test/src/main/java/com/redhat/service/smartevents/performance/webhook/models/Event.java, integration-tests/webhook-perf-test/src/main/java/com/redhat/service/smartevents/performance/webhook/models/WebhookRequest.java, integration-tests/webhook-perf-test/src/main/java/com/redhat/service/smartevents/performance/webhook/services/WebhookServiceImpl.java, integration-tests/webhook-perf-test/src/test/java/com/redhat/service/smartevents/WebhookResourceTest.java
[MGDOBR-1219](https://issues.redhat.com/browse/MGDOBR-1219)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1219 Remove lombok from WebHook test module

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1214: Operator: Split (API) versioned artifacts into sub-modules (#1308)
=> MGDOBR-1214: Operator: Split (API) versioned artifacts into sub-modules (#1308) - Update kustomization images

manager-parent/manager-core/src/main/java/com/redhat/service/smartevents/manager/core/services/ShardServiceImpl.java, manager-parent/manager-core/src/test/java/com/redhat/service/smartevents/manager/core/services/ShardServiceTest.java, manager-parent/manager-core/src/test/resources/application.properties
[MGDOBR-1241](https://issues.redhat.com/browse/MGDOBR-1241)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1241 Automatically update Shard router canonical hostname

manager-parent/manager-core/src/main/java/com/redhat/service/smartevents/manager/core/metrics/ManagerMetricsService.java, manager-parent/manager-core/src/main/java/com/redhat/service/smartevents/manager/core/models/ManagedResource.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/metrics/ManagedResourceOperationMapper.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/metrics/ManagerMetricsServiceV1.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/metrics/MetricsServiceImpl.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/models/ManagedDefinedResourceV1.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/models/ManagedResourceV1.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/persistence/models/Bridge.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/persistence/models/ConnectorEntity.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/persistence/models/Processor.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/services/BridgesServiceImpl.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/services/ProcessorServiceImpl.java, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/workers/resources/AbstractWorker.java, manager-parent/manager-v1/src/test/java/com/redhat/service/smartevents/manager/v1/metrics/ManagedResourceOperationMapperTest.java, manager-parent/manager-v1/src/test/java/com/redhat/service/smartevents/manager/v1/metrics/MetricsServiceImplTest.java
[https://issues.redhat.com/browse/MGDOBR-1263](https://issues.redhat.com/browse/MGDOBR-1263)
This PR moves use of `ManagedResourceStatus` on `ManagedResource` out of `-core` and into only `-v1`.
`-v2` is to use a set of (yet to be completely defined) `Condition` objects to define the _state_ at a more granular level.
<details>
<summary>
</summary>
Comment with `/deploy …
=> MGDOBR-1263: Remove ManagedResourceStatus from ManagedResource

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1263: Remove ManagedResourceStatus from ManagedResource (#1338)
=> MGDOBR-1263: Remove ManagedResourceStatus from ManagedResource (#1338) - Update kustomization images

.github/actions/kind/action.yml, .github/actions/start-aws-runner/action.yml, .github/actions/stop-aws-runner/action.yml, .github/kind-config.yaml, .github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, .github/workflows/Upgrade-CI.yml
[MGDOBR-1266](https://issues.redhat.com/browse/MGDOBR-1266)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1266 Migrate GitHub Actions to use AWS runner

.github/actions/kind/action.yml, .github/workflows/Manager-CI.yaml, .github/workflows/Operator-CI.yaml, .github/workflows/Upgrade-CI.yml, dev/bin/camel-k-installer.sh
[MGDOBR-1221](https://issues.redhat.com/browse/MGDOBR-1221)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1221: install Camel K in CI pipelines

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1270: add v2 database (#1354)
=> MGDOBR-1270: add v2 database (#1354) - Update kustomization images

.github/pull_request_template.md
Update template msg to avoid conflit with CPaaS pipeline
<details>
<summary>
</summary>
</details>
=> Update template msg

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1283: introduce AMS limits for v2 (#1358)
=> MGDOBR-1283: introduce AMS limits for v2 (#1358) - Update kustomization images

app-interface/manifests/rhose-fleet-manager.yml, dev/README.md, dev/bin/configure.sh, dev/bin/localconfig-example, dev/bin/manager-run.sh, manager-parent/manager-v1/src/main/java/com/redhat/service/smartevents/manager/v1/connectors/ConnectorsOidcClient.java, manager-parent/manager-v1/src/main/resources/application.properties
[MGDOBR-1212](https://issues.redhat.com/browse/MGDOBR-1212)
Replace ConnectorsOidcClient offline-token authentication with credentials authentication
=> MGDOBR-1212 - Replace offline-token authentication with credentials

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1256: [C]RUD bridge V2 (#1367)
=> MGDOBR-1256: [C]RUD bridge V2 (#1367) - Update kustomization images

.github/workflows/Manager-CI-v1.yaml, .github/workflows/Manager-CI-v2.yaml
[MGDOBR-1236](https://issues.redhat.com/browse/MGDOBR-1236)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1236: use distinct concurrency group in Manager CI

.github/workflows/Webhook-Cleanup.yml
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Run WebHook cleanup every hour

scripts/dependencies/install_dependencies.sh, scripts/dependencies/servicemesh/tracingSub.yaml
[MGDOBR-1293](https://issues.redhat.com/browse/MGDOBR-1293)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1293 Upgrade Jaeger operator version to v1.39.0-3

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1259: Processor: API [C]RUD operation (#1364)
=> MGDOBR-1259: Processor: API [C]RUD operation (#1364) - Update kustomization images

dev/bin/interaction/create-processor-v2.sh
[MGDOBR-1289](https://issues.redhat.com/browse/MGDOBR-1289)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1289: add create-processor-v2.sh script

.github/actions/start-aws-runner/action.yml, .github/workflows/Manager-CI-v1.yaml, .github/workflows/Manager-CI-v2.yaml, .github/workflows/Operator-CI-v1.yaml, .github/workflows/Upgrade-CI.yml
[MGDOBR-1272](https://issues.redhat.com/browse/MGDOBR-1272)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1272: switch GHA to ENG AWS account

.github/workflows/production-cluster-check.yml
[MGDOBR-1236](https://issues.redhat.com/browse/MGDOBR-1236)
A follow-up to https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1356 updating the production cluster check. To be merged after production is rebased to the changes from https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1356.
<details>
<summary>
</summary>
Comment with `/deploy …
=> MGDOBR-1236: update production CI to manager int. tests changes

app-interface/cronjobs/rhose-stage-prolong.yml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1128: add stage cron job

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/BridgesAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/BridgesServiceTest.java
<details>
<summary>
</summary>
</details>
=> MGDOBR-1303: return null modifiedAt bridge if it was just created

.github/workflows/production-cluster-check.yml
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Use prod branch for prod e2e tests

.github/workflows/production-cluster-check.yml
…es (#1394)"
This reverts commit 62ad25f02f2f782a5039e49674baa00aa1d7dce0.
<details>
<summary>
</summary>
</details>
=> MGDOBR-1236: update production CI to manager int. tests change - REVERT

.github/workflows/production-cluster-check.yml
<details>
<summary>
</summary>
</details>
=> NO JIRA Adjust GHA production CI to reflect module structure of prod branch

shard-operator-parent/shard-operator-v2/pom.xml
<details>
<summary>
</summary>
</details>
=> Fix CPaaS compilation error

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/BridgeDAO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ProcessorDAO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Bridge.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/persistence/dao/BridgeDAOTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/BridgesServiceTest.java
[https://issues.redhat.com/browse/MGDOBR-1259](https://issues.redhat.com/browse/MGDOBR-1259)
- [x ] Pull Request contains description of the issue
<details>
<summary>
</summary>
</details>
=> MGDOBR-1259: Processor: API [C]RUD operation. Implement missing BridgeService methods

shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeService.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeServiceImpl.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/controllers/ManagedBridgeController.java, shard-operator-parent/shard-operator-v2/src/main/resources/application.properties, shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeServiceImplTest.java, shard-operator-parent/shard-operator-v2/src/test/resources/application.properties
[MGDOBR-1244](https://issues.redhat.com/browse/MGDOBR-1244)
This PR continues the re-use of the v1 data plane code and exposes an Ingress when a ManagedBridge resource is created.
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1244] Exposed Ingress when a ManagedBridge Resource is created

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1244] Exposed Ingress when a ManagedBridge Resource is created (#1387)
=> [MGDOBR-1244] Exposed Ingress when a ManagedBridge Resource is created (#1387) - Update kustomization images

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/BridgesAPI.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/BridgesAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[MGDOBR-1318](https://issues.redhat.com/browse/MGDOBR-1318)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1318: add get bridge v2

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1261: Processor: API CR[U]D operation (#1409)
=> MGDOBR-1261: Processor: API CR[U]D operation (#1409) - Update kustomization images

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImpl.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/workers/resources/ProcessorWorker.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImplTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-1320](https://issues.redhat.com/browse/MGDOBR-1320)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1320: Add Processor Worker for dependency management

manager-parent/manager-v1/src/test/java/com/redhat/service/smartevents/manager/v1/utils/DatabaseManagerUtils.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/BridgesAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeServiceImpl.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImpl.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/utils/StatusUtilities.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/BridgesAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/BridgesServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/DatabaseManagerUtils.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[MGDOBR-1319](https://issues.redhat.com/browse/MGDOBR-1319)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1319: Delete bridge V2

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1319: Delete bridge V2 (#1420)
=> MGDOBR-1319: Delete bridge V2 (#1420) - Update kustomization images

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/utils/StatusUtilities.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/StatusUtilitiesTest.java
[https://issues.redhat.com/browse/MGDOBR-1321](https://issues.redhat.com/browse/MGDOBR-1321)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1321: v2: Processor.toDTO: Status message should filter Conditions

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/ProcessorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/ProcessorAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImplTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[https://issues.redhat.com/browse/MGDOBR-1262](https://issues.redhat.com/browse/MGDOBR-1262)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1262: Processor: API CRU[D] operation

.gitignore
NO JIRA.
<details>
<summary>
</summary>
</details>
=> Ignore the kamel-x.xx.x file created using minikube setup

docker/Dockerfile.appsre, docker/Dockerfile.jvm, executor/pom.xml, integration-tests/manager-integration-tests/manager-integration-tests-v1/pom.xml, integration-tests/manager-integration-tests/manager-integration-tests-v2/pom.xml, integration-tests/shard-operator-integration-tests/shard-operator-integration-tests-v1/pom.xml, manager-parent/manager/pom.xml, processor/processor-configuration/src/main/java/com/redhat/service/smartevents/processor/ProcessorCatalogServiceImpl.java, shard-operator-parent/shard-operator/pom.xml
[MGDOBR-1331](https://issues.redhat.com/browse/MGDOBR-1331)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1331 Use uber-jar for smart events deliverables

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ProcessorDAO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Processor.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/TestConstants.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ProcessorDAOTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImplTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[https://issues.redhat.com/browse/MGDOBR-1315](https://issues.redhat.com/browse/MGDOBR-1315)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1315: ShardAPI: GET Processors

integration-tests/manager-integration-tests/manager-integration-tests-v1/run-local-tests.sh, integration-tests/manager-integration-tests/manager-integration-tests-v2/run-local-tests.sh, integration-tests/shard-operator-integration-tests/shard-operator-integration-tests-v1/run-local-tests.sh
<details>
<summary>
</summary>
</details>
=> [NO JIRA] Fix run-local-tests.sh

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1315: ShardAPI: GET Processors (#1426)
=> MGDOBR-1315: ShardAPI: GET Processors (#1426) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1299] Increase Test Case Coverage of Shard Operator core (#1395)
=> [MGDOBR-1299] Increase Test Case Coverage of Shard Operator core (#1395) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1324: ShardAPI GET Bridges (#1430)
=> MGDOBR-1324: ShardAPI GET Bridges (#1430) - Update kustomization images

app-interface/cronjobs/rhose-stage-prolong.yml, app-interface/dashboards/grafana-dashboard-rhose-cronjob-errors.yaml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1128: add cronjob grafana dashboard

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/prod/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1342: migrate to a dedicated istio api gateway (#1446)
=> MGDOBR-1342: migrate to a dedicated istio api gateway (#1446) - Update kustomization images

infra-parent/infra-v2/src/main/java/com/redhat/service/smartevents/infra/v2/api/models/dto/ConditionDTO.java, infra-parent/infra-v2/src/main/java/com/redhat/service/smartevents/infra/v2/api/models/dto/ProcessorStatusDTO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Condition.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/ProcessorServiceImplTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[https://issues.redhat.com/browse/MGDOBR-1316(https://issues.redhat.com/browse/MGDOBR-1316)
@vaibhavjainwiz I've preempted `ProcessorUpdateDTO` you may be writing for [MGDOBR-1252](https://issues.redhat.com/browse/MGDOBR-1252)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1316: ShardAPI: POST Processor updates

manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPITest.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeSyncServiceImpl.java, shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/ManagerClientTest.java
<details>
<summary>
</summary>
</details>
=> NO-JIRA: fix merge conflicts

app-interface/cronjobs/rhose-stage-prolong.yml
<details>
<summary>
</summary>
</details>
=> MGDOBR-1128: use an allowed image for the cronjob

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1346: ShardAPI POST update Bridges (#1451)
=> MGDOBR-1346: ShardAPI POST update Bridges (#1451) - Update kustomization images

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1252] - Update Control Plane with ManagedProcessor status (#1453)
=> [MGDOBR-1252] - Update Control Plane with ManagedProcessor status (#1453) - Update kustomization images

manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardBridgesSyncSegmentationAPITest.java
== NO JIRA ==
Test could not be added to v2 until support for `Bridge`'s was more complete.
The test itself is just copied from v1.
<details>
<summary>
</summary>
</details>
=> Restore missing test now support for Bridges in v2 is more complete.

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/BridgeServiceImpl.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/BridgesServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java
[https://issues.redhat.com/browse/MGDOBR-1284](https://issues.redhat.com/browse/MGDOBR-1284)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1284: Support errors in BridgeResponse

build-parent/pom.xml
follow up with #1466 1467
Fix dependency issues
<details>
<summary>
</summary>
</details>
=> MGDOBR-1341: bump java operator sdk 4.0.5 and quarkus 2.13.5

shard-operator-parent/shard-operator-core/pom.xml, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/SecretRestartHandler.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/observability/ObservabilitySetupService.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/providers/TemplateProvider.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/providers/TemplateProviderImpl.java, shard-operator-parent/shard-operator-core/src/main/resources/application.properties, shard-operator-parent/shard-operator-core/src/main/resources/templates/observability-secret.yaml, shard-operator-parent/shard-operator-core/src/test/java/com/redhat/service/smartevents/shard/operator/core/observability/ObservabilitySetupServiceForTests.java, shard-operator-parent/shard-operator-core/src/test/java/com/redhat/service/smartevents/shard/operator/core/observability/ObservabilitySetupServiceTest.java, shard-operator-parent/shard-operator-v1/pom.xml, shard-operator-parent/shard-operator-v2/pom.xml
[https://issues.redhat.com/browse/MGDOBR-1101](https://issues.redhat.com/browse/MGDOBR-1101)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1101: Observability: Generate Observability Operator secret in RHOSE

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1341: Fix dependency issues (#1473)
=> MGDOBR-1341: Fix dependency issues (#1473) - Update kustomization images

.github/workflows/production-cluster-check.yml
[MGDOBR-1236](https://issues.redhat.com/browse/MGDOBR-1236)
A follow-up to https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1356 updating the production cluster check. To be merged after production is rebased to the changes from https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1356 - added the `do not merge` label to make it more obvious.
This PR is a replacement for https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1394 which was merged before the prod branch was rebased and had to be reverted.
<details>
<summary>
</summary>
- <b>Run the end to end pipeline</b> …
=> MGDOBR-1236: update production CI to manager int. tests changes (#1394)

kustomize/overlays/perf/awssm-secret.yaml, kustomize/overlays/perf/kustomization.yaml, kustomize/overlays/perf/manager/patches/deploy.yaml, kustomize/overlays/perf/namespace.yaml, kustomize/overlays/perf/secrets/cluster-secret-store.yaml, kustomize/overlays/perf/secrets/event-bridge-manager-secrets.yaml, kustomize/overlays/perf/secrets/kustomization.yaml, scripts/dependencies/external-secrets/externalSecretsSub.yaml, scripts/dependencies/external-secrets/kustomization.yaml, scripts/dependencies/external-secrets/resources/operator-config.yaml, scripts/dependencies/install_manager_dependencies.sh
[MGDOBR-855](https://issues.redhat.com/browse/MGDOBR-855)
<details>
<summary>
</summary>
</details>
=> MGDOBR-855 Prepare performance cluster deployment scripts

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1246] - Delete Bridge Resources when a ManagedBridge CR is deleted (#1463)
=> [MGDOBR-1246] - Delete Bridge Resources when a ManagedBridge CR is deleted (#1463) - Update kustomization images

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/requests/ConnectorRequest.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ConnectorResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SinkConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SinkConnectorResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SourceConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SourceConnectorResponse.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java, openapi/smartevents_mgmt_v2.yaml
[MGDOBR-1371](https://issues.redhat.com/browse/MGDOBR-1371)
This PR aims to scaffold the sink/source connectors api according to the design document defined in MGDOBR-1350/MGDOBR-1351
The request for a new source/sink processor is like
```json
{
"name": "<the name>",
"connector_type_id": "<the connector type>",
"connector": {
"<connector specific property #1>": "<the value>",
"<connector specific property #2>": "<the value>",    
}
}
```
The SourceConnectorResponse is like
```json
{
"kind": "SourceConnector",
"id": "<the id>", 
"href": "<href to resource>",
"name": "<the name>",
"connector_type_id": "<the connector type>",
"connector": {
"<connector specific property #1>": "<the value>",
"<connector specific property #2>": "<the value>",    
},
"status_message" : "<the message in case of …
```
=> MGDOBR-1371: scaffold sink/source connectors api in fleet manager

infra-parent/infra-core/src/main/java/com/redhat/service/smartevents/infra/core/models/responses/BaseResponse.java, infra-parent/infra-core/src/main/java/com/redhat/service/smartevents/infra/core/models/responses/ErrorResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/BridgeResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ProcessorResponse.java, openapi/smartevents_mgmt_v1.yaml, openapi/smartevents_mgmt_v2.yaml
[https://issues.redhat.com/browse/MGDOBR-1373](https://issues.redhat.com/browse/MGDOBR-1373)
- [x ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
<details>
<summary>
</summary>
</details>
=> MGDOBR-1373: Some Response classes override the name property

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1248] Create Camel-K Resources when a ManagedProcessor CR is created (#1366)
=> [MGDOBR-1248] Create Camel-K Resources when a ManagedProcessor CR is created (#1366) - Update kustomization images

openapi/smartevents_mgmt_v2.yaml, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/IstioSetupService.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/gateway/GatewaySpec.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/gateway/GatewaySpecSelector.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/gateway/GatewaySpecServer.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/gateway/GatewaySpecServerPort.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/requestauthentication/RequestAuthenticationSpec.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/requestauthentication/RequestAuthenticationSpecJWTRule.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceDestination.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceHttp.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceMatch.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServicePort.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceRoute.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceSpec.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/istio/virtualservice/VirtualServiceURI.java, shard-operator-parent/shard-operator-v2/pom.xml
https://issues.redhat.com/browse/MGDOBR-1248
<details>
<summary>
</summary>
</details>
=> [MGDOBR-1248] - Add ManagedProcessor in CPaaS pipeline

app-interface/app_sre_cronjob_runner_build_push.sh, app-interface/cronjobs/Dockerfile.cronjobs, app-interface/cronjobs/rhose-stage-prolong.yml
We need to use a custom image for the CronJob and the recommended way of building it is through a CI job.
<details>
<summary>
</summary>
</details>
=> MGDOBR-1128: add script for building cronjob runner image

shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/controllers/ManagedProcessorController.java
Follows up on #1477 and #1366
<details>
<summary>
</summary>
</details>
=> Fix existing code in main following merge of MGDOBR-1297

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1340: ProcessorService: Restore metrics capture (#1445)
=> MGDOBR-1340: ProcessorService: Restore metrics capture (#1445) - Update kustomization images

dev/docker-compose/prometheus/prometheus.yml
No JIRA. Preparatory for Observability work.
<details>
<summary>
</summary>
</details>
=> Add Shard to Prometheus's metrics scrape configuration

integration-tests/integration-tests-common/src/main/java/com/redhat/service/smartevents/integration/tests/context/TestContext.java
[MGDOBR-1273](https://issues.redhat.com/browse/MGDOBR-1273)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1273 Don't serialize OpenShiftClient in E2E tests

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR [MGDOBR-1404] Revert rename of migration to fix control plane deployment (#1505)
=> [MGDOBR-1404] Revert rename of migration to fix control plane deployment (#1505) - Update kustomization images

infra-parent/infra-v2/src/main/java/com/redhat/service/smartevents/infra/v2/api/models/DefaultConditions.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/SinkConnectorService.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/AbstractConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/SinkConnectorServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[MGDOBR-1384](https://issues.redhat.com/browse/MGDOBR-1384)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1384: add POST create sink connector feature

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1384: add POST create sink connector feature (#1512)
=> MGDOBR-1384: add POST create sink connector feature (#1512) - Update kustomization images

integration-tests/shard-operator-integration-tests/shard-operator-integration-tests-v2/run-local-tests.sh
Fix path to bin directory in shard-v2 tests.
=> [no JIRA] Fix path to bin directory in shard-v2 tests

infra-parent/infra-core/src/main/java/com/redhat/service/smartevents/infra/core/models/responses/ListResponse.java, infra-parent/infra-core/src/main/java/com/redhat/service/smartevents/infra/core/models/responses/PagedListResponse.java, infra-parent/infra-v2/src/main/java/com/redhat/service/smartevents/infra/v2/api/models/DefaultConditions.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPI.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/ConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SinkConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/models/responses/SourceConnectorListResponse.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ConnectorDAO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Connector.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ConnectorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/SinkConnectorService.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/SourceConnectorService.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/AbstractConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/persistence/dao/AbstractConnectorDAOTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/SinkConnectorServiceTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java
[MGDOBR-1394](https://issues.redhat.com/browse/MGDOBR-1394)
This PR includes https://issues.redhat.com/browse/MGDOBR-1398 as the 99% of the implementation is shared between sinks and sources. Given that it was just a matter of binding the api with the service, I included it in this PR as well.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when the PR has …
=> MGDOBR-1394: add GET source/sink connectors feature in V2 

shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/ConditionStatus.java, shard-operator-parent/shard-operator-core/src/main/java/com/redhat/service/smartevents/shard/operator/core/resources/CustomResourceStatus.java, shard-operator-parent/shard-operator-core/src/test/java/com/redhat/service/smartevents/shard/operator/core/resources/CustomResourceStatusTest.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/controllers/BridgeExecutorController.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/controllers/BridgeIngressController.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/resources/BaseResourceStatus.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/resources/BridgeExecutorStatus.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/resources/BridgeIngressStatus.java, shard-operator-parent/shard-operator-v1/src/main/java/com/redhat/service/smartevents/shard/operator/v1/resources/ConditionTypeConstants.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/controllers/BridgeExecutorControllerTest.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/controllers/BridgeIngressControllerTest.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/resources/BridgeExecutorStatusTest.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/resources/ConditionTest.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/resources/CustomResourceStatusTest.java, shard-operator-parent/shard-operator-v1/src/test/java/com/redhat/service/smartevents/shard/operator/v1/resources/FooResourceStatus.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/controllers/ManagedProcessorController.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/BaseResourceStatus.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/CamelIntegrationStatus.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/ManagedBridgeStatus.java, shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/ManagedProcessorStatus.java, shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/resources/CustomResourceStatusTest.java, shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/resources/FooResourceStatus.java
[https://issues.redhat.com/browse/MGDOBR-1391](https://issues.redhat.com/browse/MGDOBR-1391)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1391: Support Failed conditions in Data Plane

integration-tests/manager-integration-tests/manager-integration-tests-v2/src/test/resources/features/bridge.feature
<details>
<summary>
</summary>
</details>
=> MGDOBR-1413: update v2 pipeline to check that the bridge is ready

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/utils/StatusUtilities.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/internal/ShardAPITest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/StatusUtilitiesTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/workers/resources/BridgeWorkerTest.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/workers/resources/ProcessorWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-1414](https://issues.redhat.com/browse/MGDOBR-1414)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1414: v2: ManagedResourceStatus transitions different to v1

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1395: add GET connectors feature (#1532)
=> MGDOBR-1395: add GET connectors feature (#1532) - Update kustomization images

.github/workflows/Operator-CI-v2.yaml
[MGDOBR-1409](https://issues.redhat.com/browse/MGDOBR-1409)
Create new Github workflow which runs "shard-operator-integration-tests-v2" with every PR related to shard.
=> [MGDOBR-1409] Create Github workflow which runs shard v2 integration tests

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ConnectorDAO.java, manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Connector.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/persistence/dao/AbstractConnectorDAOTest.java
[MGDOBR-1394](https://issues.redhat.com/browse/MGDOBR-1394)
Fixing bug introduced in https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1519
<details>
<summary>
</summary>
</details>
=> MGDOBR-1394: fix discriminator in findByBridgeIdAndName ConnectorDAO

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/workers/resources/AbstractWorker.java, manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/workers/resources/AbstractWorkerTest.java
[https://issues.redhat.com/browse/MGDOBR-1417](https://issues.redhat.com/browse/MGDOBR-1417)
<details>
<summary>
</summary>
</details>
=> MGDOBR-1417: Observability: Record failed metric if provisioning fails in manager

kustomize/base-openshift/kustomization.yaml, kustomize/base-openshift/shard/patches/deploy-config.yaml, kustomize/overlays/ci/kustomization.yaml, kustomize/overlays/ci/shard/patches/deploy-config.yaml, kustomize/overlays/prod/kustomization.yaml, kustomize/overlays/prod/patches/deploy-config.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1421: Disable v2 shard operator sync and v2 e2e tests (#1544)
=> MGDOBR-1421: Disable v2 shard operator sync and v2 e2e tests (#1544) - Update kustomization images

manager-parent/manager-core/src/main/java/com/redhat/service/smartevents/manager/core/providers/ResourcePrefixProviderImpl.java, manager-parent/manager-core/src/test/java/com/redhat/service/smartevents/manager/core/providers/CDIResourcePrefixProviderTest.java, manager-parent/manager-core/src/test/resources/application.properties
<details>
<summary>
</summary>
</details>
=> MGDOBR-1428: Fix resource prefix validation

kustomize/base-openshift/kustomization.yaml, kustomize/overlays/ci/kustomization.yaml
This Pull request aims to update the kustomization images for the PR MGDOBR-1428: fix resource prefix validation (#1555)
=> MGDOBR-1428: fix resource prefix validation (#1555) - Update kustomization images

scripts/dependencies/serverless/serverless-catalog-source.yaml, scripts/dependencies/serverless/serverlessSub.yaml
<details>
<summary>
</summary>
</details>
=> update serverless 1.26

.github/scripts/patch_kustomization_images.py, .github/workflows/CD.yml
[MGDOBR-648](https://issues.redhat.com/browse/MGDOBR-648)
Tested here https://github.com/r00ta/pipeline-sandbox 
<details>
<summary>
</summary>
</details>
=> MGDOBR-648: Add kustomization bot
