.github/workflows/CD.yml

Jira: https://issues.redhat.com/browse/MGDOBR-25
This PR aims to add the CD pipeline so to create a new docker image when a PR is merged into main. Since at the moment we have one simple application that contains multiple modules, the pipeline will only create one image called `event-bridge-all-in-one`. 
When the different modules will be moved to different and separated applications we will deprecate `event-bridge-all-in-one` and create ad-hoc images.

MGDOBR-25: create CD pipeline

---

executor/src/main/java/com/redhat/developer/executor/Executor.java
infra/src/main/java/com/redhat/developer/infra/api/APIConstants.java
manager/src/main/java/com/redhat/developer/manager/BridgesServiceImpl.java
manager/src/main/java/com/redhat/developer/manager/ProcessorService.java
manager/src/main/java/com/redhat/developer/manager/api/internal/ShardBridgesSyncAPI.java
manager/src/main/java/com/redhat/developer/manager/api/models/requests/BridgeRequest.java
manager/src/main/java/com/redhat/developer/manager/api/models/requests/ProcessorRequest.java
manager/src/main/java/com/redhat/developer/manager/api/models/responses/ProcessorResponse.java
manager/src/main/java/com/redhat/developer/manager/api/user/BridgesAPI.java
manager/src/main/java/com/redhat/developer/manager/dao/BridgeDAO.java
manager/src/main/java/com/redhat/developer/manager/dao/ProcessorDAO.java
manager/src/main/java/com/redhat/developer/manager/exceptions/BridgeLifecycleException.java
manager/src/main/java/com/redhat/developer/manager/exceptions/ItemNotFoundException.java
manager/src/main/java/com/redhat/developer/manager/models/Bridge.java
manager/src/main/java/com/redhat/developer/manager/models/Processor.java
manager/src/main/resources/db/migration/0.1/V0.1.2__create_processor.sql
manager/src/test/java/com/redhat/developer/manager/ProcessorServiceTest.java
manager/src/test/java/com/redhat/developer/manager/api/internal/ShardBridgesSyncAPITest.java
manager/src/test/java/com/redhat/developer/manager/api/user/BridgesAPITest.java
manager/src/test/java/com/redhat/developer/manager/dao/BridgeDAOTest.java
manager/src/test/java/com/redhat/developer/manager/dao/ProcessorDAOTest.java
manager/src/test/java/com/redhat/developer/manager/models/ProcessorTest.java
manager/src/test/java/com/redhat/developer/manager/utils/DatabaseManagerUtils.java
manager/src/test/java/com/redhat/developer/manager/utils/TestUtils.java
shard/src/main/java/com/redhat/developer/shard/ManagerSyncService.java
shard/src/main/java/com/redhat/developer/shard/ManagerSyncServiceImpl.java

This PR adds an additional endpoint to our API to add support for adding a Processor to a Bridge. The supported endpoint is `/api/v1/bridges/{id}/processors`. A Processor can be created on the given Bridge instance by `POST`-ing a request to this endpoint.
The shard side of the implementation is deliberately excluded from this PR. That will be in a follow-on PR.
Other minor changes in this PR include:
- Ensuring we return a HTTP 201 Created Response code from our API in response to POST requests as per guidelines

[MGBOBR-6] Part 1: Manager-side API for adding Processor to a Bridge

---

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorService.java
manager/src/main/java/com/redhat/service/bridge/manager/api/user/BridgesAPI.java
manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java
manager/src/main/java/com/redhat/service/bridge/manager/dao/ProcessorDAO.java
manager/src/main/java/com/redhat/service/bridge/manager/models/Bridge.java
manager/src/main/java/com/redhat/service/bridge/manager/models/Processor.java
manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
manager/src/test/java/com/redhat/service/bridge/manager/api/user/BridgesAPITest.java
manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java
manager/src/test/java/com/redhat/service/bridge/manager/dao/ProcessorDAOTest.java
manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java

This PR adds the `/api/v1/bridges/{id}/processors/{processorId}` endpoint. This allows a user to retrieve details of a Processor that they have deployed to their Bridge and see if it is in the `AVAILABLE` state i.e is it processing Events sent to the Bridge.
Couple of other things to note:
- I'm not yet able to add to the Integration Test suite without the ability to delete a Processor, which will be done in another story (https://issues.redhat.com/browse/MGDOBR-8)
- Listing of the Processors on a bridge is also done as another story (https://issues.redhat.com/browse/MGDOBR-7)

[MGDOBR-9] API to allow user to GET details of a Processor

---

manager/src/main/java/com/redhat/service/bridge/manager/ProcessorService.java
manager/src/main/java/com/redhat/service/bridge/manager/api/models/responses/ProcessorListResponse.java
manager/src/main/java/com/redhat/service/bridge/manager/api/user/ProcessorsAPI.java
manager/src/main/java/com/redhat/service/bridge/manager/dao/ProcessorDAO.java
manager/src/main/java/com/redhat/service/bridge/manager/models/Processor.java
manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java
manager/src/test/java/com/redhat/service/bridge/manager/dao/ProcessorDAOTest.java
manager/src/test/java/com/redhat/service/bridge/manager/utils/TestUtils.java

This PR adds support for a `GET` to `/api/v1/bridges/{id}/processors` to list all of the Processors on a Bridge:
- The list of Processors is returned in ascending order of date submitted (oldest Processor first in the list)
- Pagination is supported using the `page` and `size` query params.

[MGDOBR-7] Add the ability to list processors on a bridge

---

infra/src/main/java/com/redhat/service/bridge/infra/models/filters/BaseFilter.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/StringBeginsWith.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/StringContains.java
infra/src/test/java/com/redhat/service/bridge/infra/models/filters/FilterFactoryTest.java

[MGDOBR-50](https://issues.redhat.com/browse/MGDOBR-50) 
This PR aims to fix the getvalueasstring method of the two filters

MGDOBR-50: fix getValueAsString and add tests

---

.github/workflows/CD.yml
.github/workflows/CI.yaml

Avoid to trigger a CD job every time a new commit is pushed on `main` branch of a fork

Skip CD job in fork repos

---

shard/src/test/java/com/redhat/service/bridge/shard/ManagerSyncServiceTest.java

[MGDOBR-73](https://issues.redhat.com/browse/MGDOBR-73) 
The `ManagerSyncServiceTest.testBridgesAreDeployed` is creating **two** Bridges instances. For each Bridge instance that is deployed, the shard will make **two** PUT requests to the `manager`: one to notify that the resource is in `PROVISIONING` state, and another one for that the resource is `AVAILABLE`. 
So **four** PUT requests are actually made by the shard, but the test was only waiting for **two** PUT requests to be sent to the server mock. The flow was like the following: 
1) two PUT requests are received (for example: bridge `myName-2` is provisioning and bridge `myName-2` is available). 
2) the test verifies that 
```java
verify(putRequestedFor(urlEqualTo(APIConstants.SHARD_API_BASE_PATH)) …
```

MGDOBR-73: fix ManagerSyncServiceTest.testBridgesAreDeployed random failures

---

manager/src/main/java/com/redhat/service/bridge/manager/dao/ProcessorDAO.java
manager/src/main/java/com/redhat/service/bridge/manager/models/Processor.java
manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java

[MGDOBR-80](https://issues.redhat.com/browse/MGDOBR-80) 
We are affected by the following bug: if a processor contains multiple filters, the queries that use a `join fetch` on the filters will produce duplicate processors. This behavior is expected and must be fixed using [this](https://developer.jboss.org/docs/DOC-15782#jive_content_id_Hibernate_does_not_return_distinct_results_for_a_query_with_outer_join_fetching_enabled_for_a_collection_even_if_I_use_the_distinct_keyword).

MGDOBR-80: filter duplicate Processors

---

FILTERS.md
executor/src/main/java/com/redhat/service/bridge/executor/filters/FilterEvaluatorFactoryFEEL.java
executor/src/test/java/com/redhat/service/bridge/executor/filters/FilterEvaluatorFEELTest.java
executor/src/test/java/com/redhat/service/bridge/executor/filters/FilterEvaluatorFactoryFEELTest.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/BaseFilter.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/FilterFactory.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/ObjectMapperFactory.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/StringBeginsWith.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/StringContains.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/StringEquals.java
infra/src/main/java/com/redhat/service/bridge/infra/models/filters/ValuesIn.java
infra/src/test/java/com/redhat/service/bridge/infra/models/filters/FilterFactoryTest.java

[https://issues.redhat.com/browse/MGDOBR-143) 
Besides adding ValuesIn class, I did some refactor, trying to keep what I though was the original idea behind BaseFilter hierarchy.  
Some rationale that might or not be shared below ;):
-  getValuesAsString method is not really needed and, if was so, I think building the string represantion belongs to filter generation, not to BaseFilter hierarchy. 
- A generic was added to BaseFilter (which requires casting to subclass, but this was already assumed by checking the class type before) so now there is a cast class but not a value cast (which I believe is part of the logic inherent to BaseFilter hierarchy, to hold the proper value data type in the child filter)   
- ValuesIn (I name it following the type-operator convention of other BaseFilter …

[MGDOBR-143] Adding IN filter

---

shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/resources/BridgeIngress.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/BridgeIngressServiceTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressControllerTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/providers/TemplateProviderTest.java

Signed-off-by: Ricardo Zanini <zanini@redhat.com>
[MGDOBR-156](https://issues.redhat.com/browse/MGDOBR-156) 
Small refactoring for `BridgeIngress` CR builder. Unfortunately, we can't have a private constructor since fabric8 creates the CR via reflection and needs the public constructor. Our internal client code was refactored to use the builder instead since this object is quite hard to create and keep track of.

[MGDOBR-156] BridgeIngress builder refactoring

---

.github/workflows/Operator-CI.yaml
pom.xml
shard-operator-integration-tests/README.md
shard-operator-integration-tests/pom.xml
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/RunCucumberTest.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/common/Context.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/common/GlobalContext.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/common/TimeUtils.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/steps/BridgeIngressSteps.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/steps/Hooks.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/steps/KubernetesSteps.java
shard-operator-integration-tests/src/test/resources/features/bridgeingress-deploy.feature
shard-operator-integration-tests/src/test/resources/junit-platform.properties
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/networking/KubernetesNetworkingService.java

[MGDOBR-147](https://issues.redhat.com/browse/MGDOBR-147) 
Initial implementation of Shard operator integration tests.
The tests focus specifically on operator functionality, the BridgeIngress images were replaced with dummy ones as original images require Kafka - is currently not available for CI tests.
@r00ta  Currently integration tests aren't added to parent module list as the integration tests are executed by default there. Running this module without prepared environment will cause test failures. Would it have more sense to add the module into module list, allowing tests to be executed only when parameter/profile is activated?

MGDOBR-147: Create basic test suite for Shard operator integration tests

---

DEMO.md
actions/src/main/java/com/redhat/service/bridge/actions/kafkatopic/KafkaTopicAction.java
actions/src/main/java/com/redhat/service/bridge/actions/kafkatopic/KafkaTopicInvoker.java
actions/src/main/java/com/redhat/service/bridge/actions/webhook/WebhookAction.java
actions/src/test/java/com/redhat/service/bridge/actions/kafkatopic/KafkaTopicActionTest.java
actions/src/test/java/com/redhat/service/bridge/actions/kafkatopic/KafkaTopicActionValidatorTest.java
actions/src/test/java/com/redhat/service/bridge/actions/kafkatopic/KafkaTopicInvokerTest.java
actions/src/test/java/com/redhat/service/bridge/actions/webhook/WebhookActionTest.java
executor/src/main/java/com/redhat/service/bridge/executor/Executor.java
executor/src/main/java/com/redhat/service/bridge/executor/ExecutorsService.java
executor/src/test/java/com/redhat/service/bridge/executor/ExecutorServiceTest.java
executor/src/test/java/com/redhat/service/bridge/executor/ExecutorTest.java
infra/src/main/java/com/redhat/service/bridge/infra/models/dto/ProcessorDTO.java
integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/End2EndTestIT.java
kustomize/base/shard/resources/bridgeexecutors.com.redhat.service.bridge-v1.yml
manager/src/main/java/com/redhat/service/bridge/manager/ProcessorServiceImpl.java
manager/src/main/java/com/redhat/service/bridge/manager/api/internal/ShardBridgesSyncAPI.java
manager/src/main/java/com/redhat/service/bridge/manager/api/models/responses/ProcessorResponse.java
manager/src/test/java/com/redhat/service/bridge/manager/ProcessorServiceTest.java
manager/src/test/java/com/redhat/service/bridge/manager/api/user/ProcessorAPITest.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/BridgeExecutorServiceImpl.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/resources/BridgeExecutor.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/resources/BridgeExecutorSpec.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/AbstractShardWireMockTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/BridgeExecutorServiceTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/TestSupport.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorControllerTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/providers/TemplateProviderTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/resources/BridgeExecutorTest.java

[MGDOBR-39](https://issues.redhat.com/browse/MGDOBR-39) 
This PR removes the BridgeDTO from the ProcessorDTO. Only the `bridgeId` and the `customerId` is stored in the ProcessorDTO. The `BridgeResponse` is removed from the `ProcessorResponse` as well. 

MGDOBR-39: Remove BridgeDTO from ProcessorDTO and ProcessorResponse

---

.github/workflows/Operator-CI.yaml
shard-operator-integration-tests/README.md
shard-operator-integration-tests/pom.xml
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/common/Context.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/logs/EventCollector.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/logs/LogCollector.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/logs/LogConfig.java
shard-operator-integration-tests/src/test/java/com/redhat/service/bridge/shard/operator/cucumber/steps/Hooks.java

[MGDOBR-177](https://issues.redhat.com/browse/MGDOBR-177) 
Integration test logs are stored in `target/logs` directory. Namespace events are stored too.

MGDOBR-177: Store logs and events of Shard operator integration tests

---

shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorController.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressController.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/monitoring/ServiceMonitorService.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/monitoring/ServiceMonitorServiceImpl.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/resources/ConditionMessages.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/monitoring/ServiceMonitorServiceTest.java

Signed-off-by: Ricardo Zanini <zanini@redhat.com>
[MGDOBR-163](https://issues.redhat.com/browse/MGDOBR-163) 
Small change to `BridgeExecutor` to include `ServiceMonitor`. If Prometheus is not available, the CR will change its status to `Ready: false` and will notify the manager, so the component status will be `FAILED`.
I tried to do a small refactoring of the Controllers since they have almost the same algorithm. It's fairly easy to do, but the change would be huge. I'd rather have it in another PR. @r00ta @robpblake wdyt? I can open a JIRA to make the `ShardController` and `ShardResource` to manage the common bits between these two.

[MGDOBR-163] Adding Pormetheus ServiceMonitor to BridgeExecutor

---

manager/src/main/resources/application.properties
rhoas-client/src/main/resources/application.properties

This is the cleanest solution I found to quickly fix the start of the manager with disabled RHOAS, without changing the existing code too much.
[MGDOBR-222](https://issues.redhat.com/browse/MGDOBR-222) 

MGDOBR-222: fix manager start with disabled rhoas

---

shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressController.java
shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/utils/DeploymentStatusUtils.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/ManagerSyncServiceTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/controllers/BridgeIngressControllerTest.java
shard-operator/src/test/java/com/redhat/service/bridge/shard/operator/utils/KubernetesResourcePatcher.java

[MGDOBR-114](https://issues.redhat.com/browse/MGDOBR-114) 
This PR adds in a notification from Fleet Shard to Fleet Manager in the Event that the Ingress `Deployment` fails to deploy. A Failure is determined by the `Condition`, `ReplicaFailure` having the value `True` on the status of the `Deployment` resource.
This PR does not take into account the duration of the time taken to deploy the Ingress. At the minute, the time limit for deploying the Ingress is unbounded and we will address timeout in [MGDOBR-255](https://issues.redhat.com/browse/MGDOBR-255).

[MGDOBR-114] Notify Manager if Bridge Ingress Fails To Deploy

---

DEMO.md

When I was going through the "DEMO.md" readme, I've found out two possible problems which can be improved:
1. There are wrong quotes around the authentication header in the send event request
2. It would be good to save the endpoint URL to environment variable and use it in later requests. It will follow the same principle as we do with the bridge and the processor ids.

MGDOBR-281 - Demo readme improvements

---

shard-operator-integration-tests/pom.xml

Defining Cucumber version definition from build-parent/pom.xml for shared-operator-integration-tests
[MGDOBR-262](https://issues.redhat.com/browse/MGDOBR-262) 

MGDOBR 262: Define Cucumber version definition from build-parent/pom.xml for shared-operator-integration-tests

---

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/End2EndTestITStep.java
integration-tests/src/test/resources/features/end2endtestit.feature

[MGDOBR-263](https://issues.redhat.com/browse/MGDOBR-263) 
Currently implemented tests ([MGDOBR-205](https://issues.redhat.com/browse/MGDOBR-205)) depend on each other to be executed in specific order.
This makes them fragile - if a test fails then all subsequent tests will most likely fail too. Also it is not possible to execute a specific test, user needs to execute whole test suite even when interested in one test result.
Purpose of this JIRA is to convert tests to be self contained - every test should be executed separately regardless of other tests or execution order. Every test will be responsible to setup the environment needed.
Acceptance Criteria
- Every test can be executed separately.
- !!!CHANGE: "Every test should clean its resources in case of a successful execution (cleanup …

MGDOBR-263 - Refactor integration tests to be self contained

---

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/common/BridgeCommon.java
integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/End2EndTestITStep.java

[MGDOBR-264](https://issues.redhat.com/browse/MGDOBR-264) 
- Added cleanup method which will delete the created resources in tests for each scenarios and as well as if any test fails
- Added listProcessors method to track the associated processor for the bridge before deletion

MGDOBR-264 - cleanup created resource if test fails

---

manager/src/main/java/com/redhat/service/bridge/manager/connectors/creation/CreateConnectorWorker.java

[MGDOBR-199](https://issues.redhat.com/browse/MGDOBR-199) 
Local test didn't show the bug as the `manager_run.sh` script sets both the `kafka.bootstrap.servers`  and the `managed-connectors.kafka.bootstrap.servers` to the same value
<details>
<summary>
</summary>
</details>

MGDOBR-199 Fix property of kafkaBootstrapServer

---

.github/workflows/dev-cluster-check.yml

[MGDOBR-341](https://issues.redhat.com/browse/MGDOBR-341) 
Limit "dev-cluster-check" Github workflow to run only on root repository. It will not run on forked repositories. 
- [*] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [NA] All new functionality is tested
- [*] Pull Request contains description of the …

MGDOBR-341 - Limit dev-cluster-check to run only on root repository

---

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java

Extended HTTP response code to check response produced by OpenShift route (HTTP 503).
<details>
<summary>
</summary>
</details>

Fix unavailable Ingress step for integration tests

---

TRANSFORMATIONS.md

Link to quarkus.io instead of quarkus.pro, which is an inofficial site

Link to official Quarkus site

---

manager/src/main/java/com/redhat/service/bridge/manager/RhoasServiceImpl.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/RhoasClientImpl.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/exceptions/AppServicesException.java
rhoas-client/src/test/java/com/redhat/service/bridge/rhoas/RhoasClientTestBase.java
rhoas-client/src/test/java/com/redhat/service/bridge/rhoas/RhoasClientWithBrokenTopicTest.java
rhoas-client/src/test/java/com/redhat/service/bridge/rhoas/RhoasTestBase.java
test-utils/src/main/java/com/redhat/service/bridge/test/rhoas/KafkaInstanceAdminMockServerConfigurator.java

[Deletion of Bridge shouldn't fail when Topic is already deleted](https://issues.redhat.com/browse/MGDOBR-410) 
<details>
<summary>
</summary>
</details>

MGDOBR-410 Deletion of Bridge shouldn't fail when Topic is already deleted

---

integration-tests/src/test/java/com/redhat/service/bridge/integration/tests/steps/IngressSteps.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/KafkaInstanceAdminClient.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/KafkaInstanceAdminClientImpl.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/RhoasClient.java
rhoas-client/src/main/java/com/redhat/service/bridge/rhoas/RhoasClientImpl.java
rhoas-client/src/test/java/com/redhat/service/bridge/rhoas/RhoasClientWithBrokenTopicTest.java
rhoas-client/src/test/java/com/redhat/service/bridge/rhoas/RhoasTestBase.java
test-utils/src/main/java/com/redhat/service/bridge/test/rhoas/AbstractApiMockServerConfigurator.java
test-utils/src/main/java/com/redhat/service/bridge/test/rhoas/KafkaInstanceAdminMockServerConfigurator.java

[MGDOBR-430](https://issues.redhat.com/browse/MGDOBR-430) 
<details>
<summary>
</summary>
</details>

MGDOBR-430: Slack Processor creation is failing with Error when calling Kafka instance TopicsApi (status=409)

---

integration-tests/src/test/resources/features/bridge.feature
integration-tests/src/test/resources/features/ingress.feature
integration-tests/src/test/resources/features/processor-template.feature
integration-tests/src/test/resources/features/processor.feature

[MGDOBR-458](https://issues.redhat.com/browse/MGDOBR-458)
<details>
<summary>
</summary>
</details>

MGDOBR-458 Extend Bridge creation timeout in integration tests

---

.github/workflows/CI.yaml

[MGDOBR-506](https://issues.redhat.com/browse/MGDOBR-506)
This PR brings pull request sonar analysis available on sonarcloud console - https://sonarcloud.io/project/overview?id=5733d9e2be6485d52ffa08870cabdee0_sandbox
If the results won't be avaiable in github ui, I can investigate more.
In my testing job, we can see:
```
mvn -B sonar:sonar -Dsonar.projectKey=5733d9e2be6485d52ffa08870cabdee0_sandbox \
-Dsonar.organization=5733d9e2be6485d52ffa08870cabdee0 \
-Dsonar.host.url=https://sonarcloud.io/ \
-Dsonar.login=$SONAR_TOKEN \
-Dsonar.pullrequest.key=$PR_KEY \
-Dsonar.pullrequest.branch=$PR_BRANCH \
-Dsonar.pullrequest.base=$PR_BASE
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-1/x64
GITHUB_TOKEN: *** …
```

MGDOBR-506: sonar pullrequest specific properties

---

.github/workflows/dev-cluster-check.yml

Enable periodical dev cluster check as it seems that errors were fixed and tests are passing again. https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/actions/runs/2069804325
I've change the cron to run it only once a day. It seems enough to detect if cluster is in health state.

Enable dev cluster check

---

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ProcessorSteps.java

Added missing log entries in case Processor related waiting loop fails.
<details>
<summary>
</summary>
</details>

[NO JIRA] E2E log request in case of Processor check fail

---

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/WaitingSteps.java
integration-tests/src/test/resources/features/processor-template.feature

[MGDOBR-613](https://issues.redhat.com/browse/MGDOBR-613)
E2E tests checking update of Processor are failing intermittently.
This is caused by sending a cloud event before Processor to be updated container is fully terminated:
Once updated Processor change its container state to ready and termination of former Processor is initiated then operator returns ready state. However the terminated Processor can still process some events before fully terminated, causing random test fails.
<details>
<summary>
</summary>
Annotate the pull …

MGDOBR-613 E2E add a waiting step after Processor update

---

integration-tests/README.md
integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/common/BridgeUtils.java

Currently E2E tests use OB_TOKEN for SSO authentication. However, this token expires within 15 minutes. The goal of this Jira is to allow user to use OPENSHIFT_OFFLINE_TOKEN when running E2E tests.
Acceptance Criteria: E2E tests can be run with OPENSHIFT_OFFLINE_TOKEN.
- [*] Pull Request contains description of the …

MGDOBR-645 - Allow E2E tests to use openshift offline token

---

.github/workflows/dev-cluster-check.yml
.github/workflows/stable-cluster-check.yml

Turn on export of junits in dev/stable cluster checks. This will help us with investigation of failures.

[no jira] Enable export of junit files

---

.github/workflows/dev-cluster-long-running-bridge.yml

[MGDOBR-476](https://issues.redhat.com/browse/MGDOBR-476)
The `WEBHOOK_SITE_UUID` is not required for this CI check, however it is needed for Before hook cleaning up the WebHook site. As there is no easy way how to isolate the hooks from this suite then the simplest way is to allow hooks to be executed, providing needed properties.
<details>
<summary>
</summary>
Comment with: …

MGDOBR-476 Add WEBHOOK_SITE_UUID env variable for long running CI

---

build-parent/pom.xml

Upgraded client due to this potential breaking change 
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1013/files 
But it seems like our system is not affected
<details>
<summary>
</summary>
</details>

NO-JIRA upgrade to Managed Connector Client 0.20.0

---

kustomize/base-openshift/shard/knative/broker-network-policy.yaml
kustomize/base-openshift/shard/knative/knative-eventing.yaml
kustomize/base-openshift/shard/knative/knative-kafka.yaml
kustomize/base-openshift/shard/knative/webhook-network-policy.yaml
kustomize/base-openshift/shard/service-mesh/gateway.yaml
kustomize/base-openshift/shard/service-mesh/jwt-request-authentication.yaml
kustomize/base-openshift/shard/service-mesh/service-mesh-control-plane.yaml
kustomize/base-openshift/shard/service-mesh/service-mesh-member-roll.yaml
kustomize/base-openshift/shard/service-mesh/virtual-service-kafka-broker.yaml
kustomize/overlays/dev/kustomization.yaml
kustomize/overlays/dev/patch-with-istio-system-namespace.yaml
kustomize/overlays/dev/patch-with-knative-eventing-namespace.yaml
kustomize/overlays/stable/kustomization.yaml
kustomize/overlays/stable/patch-with-istio-system-namespace.yaml
kustomize/overlays/stable/patch-with-knative-eventing-namespace.yaml

[MGDOBR-778](https://issues.redhat.com/browse/MGDOBR-778)
I know it's not ideal, but many others have the same issue https://github.com/kubernetes-sigs/kustomize/issues/880
<details>
<summary>
</summary>
</details>

[MGDOBR-778] Kustomize overrides all the namespaces - fix knative and istio

---

dev/bin/configure.sh

[MGDOBR-534](https://issues.redhat.com/browse/MGDOBR-534)
`istioctl` is now a required tool by our dev scripts. This PR adds it to the preliminary check so that the script fails if it's not installed.

MGDOBR-534: add istioctl to required tools in dev scripts

---

manager/src/main/java/com/redhat/service/smartevents/manager/api/user/ErrorsAPI.java
manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ErrorsAPITest.java
openapi/openapi.yaml

[MGDOBR-669](https://issues.redhat.com/browse/MGDOBR-669)
In order to implement MGDOBR-669 we are removing authentication from `/error/*` endpoints like has been done in Kafka and Service Registry (you can refer to https://github.com/redhat-developer/app-services-sdk-js/blob/main/scripts/errors/fetch-errors.sh)
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> …

MGDOBR-669 Removing authentication from Error Catalog API

---

kustomize/startMinikubeDeployLocalDev.sh

That will help identifying resources created by users using single command deployment script
<details>
<summary>
</summary>
</details>

[NO JIRA] Apply resource prefix from localconfig if defined

---

.github/actions/validate_api.yaml
spectral.yaml

Add example for the job that validates API for correctness
http://api.appservices.tech/ defines OpenAPI standards that your team can follow to build Managed Services Control Plane APIs. We use spectral ruleset to check those rules. We will add validation into github actions once we get initial API validated and onboarded into sdk. 
This API meets all our standards
https://github.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/pull/200
Some of the changes that were made can be copy pasted to your project etc.
Another good example of the Java/Quarkus project that follows the standard would be SRS fleet manager:
https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/blob/main/core/src/main/resources/srs-fleet-manager.json#L546-L583
http://api.appservices.tech/spectral/

Linting For OpenAPI

---

dev/bin/minikube-start.sh

This is needed as the current version doesn't work on BSD and always modifies the `jwt-request-authentication.yaml` file, also creating a wrong backup file in the working directory
<details>
<summary>
</summary>
</details>

Fix sed used in istio script to work on BSD (macOS) 

---

app-interface/app_sre_fleet_manager_build_push.sh

[MGDOBR-838](https://issues.redhat.com/browse/MGDOBR-838)
This PR aligns the way in which we build and tag images in `app-interface` with our upstream approach to image tagging. This is to make the developer experience of deploying a change to `app-interface` easier as we can simply use the same image tag that we have running in our `dev` environment.
<details>
<summary>
</summary>
- <b>Deploy …

[MGDOBR-838] Align app-interface and upstream image tagging

---

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/BridgeSteps.java
integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/steps/ProcessorSteps.java

[MGDOBR-934](https://issues.redhat.com/browse/MGDOBR-934)
<details>
<summary>
</summary>
</details>

[MGDOBR-934] Add failFastFaillureReason in case of Awaitility failFast conditions

---

integration-tests/src/test/java/com/redhat/service/smartevents/integration/tests/resources/webhook/site/WebhookSiteResource.java

Added missing logging, that should help us identifying possible issues with webhook.site requests.
<details>
<summary>
</summary>
</details>

[NO JIRA] Logs WebHook.site request failures

---

manager/src/main/java/com/redhat/service/smartevents/manager/models/Bridge.java
manager/src/main/java/com/redhat/service/smartevents/manager/models/Processor.java
manager/src/test/java/com/redhat/service/smartevents/manager/BridgesServiceTest.java
manager/src/test/java/com/redhat/service/smartevents/manager/api/internal/ShardBridgesSyncAPITest.java
manager/src/test/java/com/redhat/service/smartevents/manager/dao/BridgeDAOTest.java
manager/src/test/java/com/redhat/service/smartevents/manager/dao/ProcessorDAOTest.java
shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceImpl.java
shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/ManagerSyncServiceMockedTest.java

[https://issues.redhat.com/browse/MGDOBR-441](https://issues.redhat.com/browse/MGDOBR-441)
I'm not entirely convinced this is the best approach and would welcome thoughts.
At the moment we have a small window of potential failure between us advising the `manager` that a resource is being provisioned and us actually asking k8s to create or replace the CRD. Once we've told k8s then we're bullet proof. I was toying with the idea of a much larger refactor that puts the "tell the manager" call and "tell k8s" much closer together; but even if they're subsequent lines there will always remain potential for failure.
What's in this PR works; but I am not convinced it adds more smell to the code than it fixes. 
*Run `mvn clean verify …

MGDOBR-441: Shard may never delete resources if it crashes after sending DELETING status call

---

app-interface/manifests/rhose-fleet-manager.yml

add SHARD_ROUTER_CANONICAL_HOSTNAME to the Openshift template
<details>
<summary>
</summary>
</details>

[MGDOBR-952] - add SHARD_ROUTER_CANONICAL_HOSTNAME to OCP Template

---

integration-tests/src/test/resources/features/action-kafka.feature

This was caused by simultaneous merge of:
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/985
and
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/899

[NO JIRA] Fix wrong step in Kafka action test

---

app-interface/manifests/rhose-fleet-manager.yml

[MGDOBR-838](https://issues.redhat.com/browse/MGDOBR-838)
Removes a hard-coded property from the Openshift Template that was incorrectly setting the DNS subdomain.
<details>
<summary>
</summary>
</details>

[MGDOBR-838] Remove hardcoded property in openshift template

---

shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/networking/OpenshiftNetworkingService.java
shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/networking/OpenshiftRouteSpecMatchesHelper.java
shard-operator/src/test/java/com/redhat/service/smartevents/shard/operator/networking/OpenshiftRouteSpecMatchesHelperTest.java

[https://issues.redhat.com/browse/MGDOBR-1037](https://issues.redhat.com/browse/MGDOBR-1037)
It's not clear what `RouteSpec` properties we should be considering in the comparison.
However, since `RouteSpec` overrides `equals(..)` delegate complete comparison to it.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a …

MGDOBR-1037: Shard should verify hostname and SSL configuration of the Route exposed for a Bridge as part of the reconcile loop

---

kustomize/base-openshift/kustomization.yaml
kustomize/overlays/ci/kustomization.yaml

This Pull request aims to update the kustomization images for the PR MGDOBR-1035: Shard does not report Bridge as Failed if Knative Broker resource does not deploy (#1126)

MGDOBR-1035: Shard does not report Bridge as Failed if Knative Broker resource does not deploy (#1126) - Update kustomization images

---

shard-operator/src/main/resources/application.properties
shard-operator/src/test/resources/application.properties

[MGDOBR-1085](https://issues.redhat.com/browse/MGDOBR-1085)
<details>
<summary>
</summary>
</details>

MGDOBR-1085: enlarge timeout for provisioning from 1 minute to 5 minutes

---

manager/src/test/java/com/redhat/service/smartevents/manager/api/user/BridgesAPITest.java

[https://issues.redhat.com/browse/MGDOBR-1113](https://issues.redhat.com/browse/MGDOBR-1113)
Additional test for Bridge creation/filtering. A test already [exists](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/manager/src/test/java/com/redhat/service/smartevents/manager/api/user/ProcessorAPITest.java#L122) for Processors.
Both tests create and query without any delay.
<details>
<summary>
</summary>
- <b>Rebase the pull request</b> …

MGDOBR-1113: Unit Test: Call to getProcessors with name filter fails when too quick after processor creation. Not an issue.

---

app-interface/manifests/rhose-fleet-manager.yml

[MGDOBR-1124](https://issues.redhat.com/browse/MGDOBR-1124)
Integer parameters must be enclosed in `{{}}` for Openshift Templates.
<details>
<summary>
</summary>
</details>

[MGDOBR-1124] Fix replicas parameter format on Openshift Template

---

executor/src/main/java/com/redhat/service/smartevents/executor/WebhookOidcClient.java
infra/src/main/java/com/redhat/service/smartevents/infra/auth/AbstractOidcClient.java
infra/src/main/java/com/redhat/service/smartevents/infra/auth/OidcSchedulerProducer.java
infra/src/test/java/com/redhat/service/smartevents/infra/AbstractOidcClientTest.java
manager/src/main/java/com/redhat/service/smartevents/manager/connectors/ConnectorsOidcClient.java
shard-operator/src/main/java/com/redhat/service/smartevents/shard/operator/EventBridgeOidcClient.java

When running with Quartz in a clustered environment the `@Scheduled` annotation causes the task to be executed on any node in the cluster. This is not what we want as we need each node to periodically refresh its own access token.
This commit replaces the Quartz scheduler with a simple in-memory ScheduledExecutorService to perform the OIDC token refresh
[MGDOBR-1122](https://issues.redhat.com/browse/MGDOBR-1122)
<details>
<summary>
</summary>
- <b>Rebase …

[MGDOBR-1122] Used in-memory scheduler for OIDC token refresh

---

app-interface/manifests/rhose-fleet-manager.yml

[MGDOBR-1121](https://issues.redhat.com/browse/MGDOBR-1121)
Simply remove the `MANAGED_CONNECTORS_TOPIC_NAME` parameter from the Openshift template as it is no longer required. The inclusion of this parameter is causing the `production` pipeline to fail as it expects the value to be present in the vault.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when …

[MGDOBR-1121] Removed the MANAGED_CONNECTORS_TOPIC_NAME env parameter from Openshift Template

---

integration-tests/src/test/resources/features/bridge.feature
integration-tests/src/test/resources/features/error-handling.feature

I have observed occasional timeouts in Bridge creation/deletion.
They seemed to be related to delay caused by Kafka timeouts.
Extending the timeouts for Bridges with error handler should stabilize the test suite.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target …

[NO JIRA] E2E tests: Adjust Bridge creation timeouts

---

kustomize/README.md
scripts/dependencies/README.md
scripts/dependencies/common_tools.sh
scripts/dependencies/install_dependencies.sh
scripts/dependencies/serverless/serverless-catalog-source.yaml
scripts/dependencies/serverless/serverless-operator-group.yaml
scripts/dependencies/serverless/serverless-system-namespace.yaml
scripts/dependencies/serverless/serverlessSub.yaml
scripts/dependencies/uninstall_dependencies.sh

JIRA: https://issues.redhat.com/browse/MGDOBR-1127
Done:
- Install serverless from midstream
- Install serverless operator in another namespace (`openshift-serverless`) than `openshift-operators`. This is the recommended way. Also, existing installations are migrated to use this namespace per the [migration document](https://github.com/openshift-knative/serverless-operator/blob/main/docs/migrating-from-product-to-midstream.md).
- Make some shell functions accept an optional namespace argument
<details>
<summary>
</summary>
Annotate the pull request with the label: `safe to …

Install serverless from midstream

---

.github/workflows/dev-cluster-check.yml
.github/workflows/production-cluster-check.yml
.github/workflows/stable-cluster-check.yml
.github/workflows/stage-cluster-check.yml

To provide buffer for test execution and accommodate more tests being executed.
<details>
<summary>
</summary>
</details>

[NO JIRA] Raise nightly CI check timeout

---

.github/actions/java-maven-setup/action.yml
.github/actions/kind/action.yml
.github/workflows/CD.yml
.github/workflows/CI-Topics-Cleanup.yml
.github/workflows/CI.yaml
.github/workflows/Managed-Connectors-Cleanup.yml
.github/workflows/Manager-CI.yaml
.github/workflows/Operator-CI.yaml
.github/workflows/Upgrade-CI.yml
.github/workflows/Webhook-Cleanup.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deploy-bot.yml
.github/workflows/dev-cluster-check.yml
.github/workflows/dev-cluster-long-running-bridge.yml
.github/workflows/openapi_update.yaml
.github/workflows/production-cluster-check.yml
.github/workflows/rebase.yml
.github/workflows/sonar.yaml
.github/workflows/stable-cluster-check.yml
.github/workflows/stage-cluster-check.yml

[MGDOBR-1152](https://issues.redhat.com/browse/MGDOBR-1152)
<details>
<summary>
</summary>
</details>

[MGDOBR-1152] - Update GH actions to use Node.js 16 and deprecated commands

---

manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/Fixtures.java

NO JIRA.
The names don't directly affect a great deal (until `Worker`'s are all added) but it's good to use the correct ones.
<details>
<summary>
</summary>
</details>

Fix Condition names used for Processors

---

.github/workflows/openapi_update.yaml

This pr enables changes to the openapi spec to be push to the core SDK repo aswell as the other SDKs.
https://issues.redhat.com/browse/MGDX-284
<details>
<summary>
</summary>
</details>

MGDX-284: now push openapi changes to core sdk

---

shard-operator-parent/shard-operator-core/pom.xml
shard-operator-parent/shard-operator-v2/pom.xml

No JIRA
I noticed `shard-operator-v2` was including some `v1` dependencies. This PR fixes it.
<details>
<summary>
</summary>
</details>

Remove v1 dependencies from v2

---

app-interface/cronjobs/rhose-stage-prolong.yml

Temporarily use the ubi8 image to workaround the chicken-egg problem with the image build being blocked by missing image. After the image is built successfully by the CI job, this needs to be reverted.
<details>
<summary>
</summary>
Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target …

MGDOBR-1128: temporarily use the ubi image for CronJob

---

app-interface/cronjobs/rhose-stage-prolong.yml

This reverts commit 8781b43d678cedea30ff91248ec7fac309e6365c.
The rhose-cronjob-runner image is now available, we can finally use it.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: revert "temporarily use the ubi image for CronJob"

---

app-interface/cronjobs/rhose-stage-prolong.yml

Temporarily increase the CronJob frequency in order to debug reaching a timeout on the SRE cluster.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: make CronJob run each hour for debugging

---

manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SinkConnectorsAPI.java
manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/api/user/SourceConnectorsAPI.java
manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/dao/ConnectorDAO.java
manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/persistence/models/Connector.java
manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorService.java
manager-parent/manager-v2/src/main/java/com/redhat/service/smartevents/manager/v2/services/ConnectorService.java
manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/api/user/AbstractConnectorsAPITest.java
manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/persistence/dao/AbstractConnectorDAOTest.java
manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/services/AbstractConnectorServiceTest.java
manager-parent/manager-v2/src/test/java/com/redhat/service/smartevents/manager/v2/utils/TestUtils.java

[MGDOBR-1395](https://issues.redhat.com/browse/MGDOBR-1395)
<details>
<summary>
</summary>
</details>

MGDOBR-1395: add GET connectors feature

---

infra-parent/infra-v2/src/main/java/com/redhat/service/smartevents/infra/v2/api/exceptions/definitions/platform/UnclassifiedConstraintViolationException.java
infra-parent/infra-v2/src/main/resources/exception/exceptionInfo-v2.json

No JIRA.. it's just something I spotted. 
<details>
<summary>
</summary>
</details>

Remove unused exception before v2 Error Catalogue gets polluted.

---

app-interface/cronjobs/Dockerfile.cronjobs

Added the user home creation as its needed by OCM.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: CronJob docker image creates a user home

---

app-interface/app_sre_cronjob_runner_build_push.sh
app-interface/cronjobs/rhose-stage-prolong.yml

The CronJob Docker image version needs to be increased.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: increase CronJob docker image version

---

integration-tests/shard-operator-integration-tests/shard-operator-integration-tests-v2/src/test/resources/features/bridge-resource.feature
kustomize/base/shard/resources/managedbridges.com.redhat.service.smartevents-v1.yml
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeServiceImpl.java
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/converters/ManagedBridgeConverter.java
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/KnativeBrokerConfigurationSpec.java
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/ManagedBridge.java
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/resources/ManagedBridgeSpec.java
shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/ManagedBridgeServiceTest.java
shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/converters/ManagedBridgeConverterTest.java
shard-operator-parent/shard-operator-v2/src/test/java/com/redhat/service/smartevents/shard/operator/v2/utils/Fixtures.java

- Removed sensitive fields from the ManagedBridge CRD and ensured that they are only written to the Secret associated with the Bridge
- Updated the ManagedBridge CRD for our kustomize overlays
- Tested the ManagedBridge converter which was originally incorrectly mapping TLS key and certificate
- Added labels to all resources created by ManagedBridgeService that allow us to easily locate them using kubectl
[MGDOBR-1335](https://issues.redhat.com/browse/MGDOBR-1335)
<details>
<summary>
</summary>
Annotate the pull request with the label: `safe to test`. If you want to run the …

[MGDOBR-1335] Removed sensitive fields from ManagedBridge CRD

---

app-interface/app_sre_cronjob_runner_build_push.sh
app-interface/cronjobs/Dockerfile.cronjobs
app-interface/cronjobs/rhose-stage-prolong.yml

Set OCM_CONFIG in the CronJob image to avoid ocm trying to store data in root.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: set OCM_CONFIG in the CronJob image

---

integration-tests/manager-integration-tests/manager-integration-tests-v2/src/test/java/com/redhat/service/smartevents/integration/tests/v2/RunCucumberTest.java
integration-tests/manager-integration-tests/manager-integration-tests-v2/src/test/resources/features/bridge.feature
shard-operator-parent/shard-operator-v2/src/main/java/com/redhat/service/smartevents/shard/operator/v2/ManagerSyncService.java
shard-operator-parent/shard-operator-v2/src/main/resources/application.properties

[MGDOBR-1421](https://issues.redhat.com/browse/MGDOBR-1421)
RIP V2
<details>
<summary>
</summary>
</details>

MGDOBR-1421: Disable v2 shard operator sync and v2 e2e tests

---

app-interface/cronjobs/rhose-stage-prolong.yml

Set back the CronJob trigger to once a day (+ limit the number of jobs in history) after debugging finished.
<details>
<summary>
</summary>
</details>

MGDOBR-1128: limit CronJob runs after debugging
